<?php
/**
 * ApplicationInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApplicationInformation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApplicationInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'application_name' => 'string',
        'application_version' => 'string',
        'application_build_number' => 'string',
        'install_referrer' => 'string',
        'package' => 'string',
        'os' => 'string',
        'apple_search_ads_attributes' => 'map[string,map[string,string]]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'application_name' => null,
        'application_version' => null,
        'application_build_number' => null,
        'install_referrer' => null,
        'package' => null,
        'os' => null,
        'apple_search_ads_attributes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'application_name' => 'application_name',
        'application_version' => 'application_version',
        'application_build_number' => 'application_build_number',
        'install_referrer' => 'install_referrer',
        'package' => 'package',
        'os' => 'os',
        'apple_search_ads_attributes' => 'apple_search_ads_attributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'application_name' => 'setApplicationName',
        'application_version' => 'setApplicationVersion',
        'application_build_number' => 'setApplicationBuildNumber',
        'install_referrer' => 'setInstallReferrer',
        'package' => 'setPackage',
        'os' => 'setOs',
        'apple_search_ads_attributes' => 'setAppleSearchAdsAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'application_name' => 'getApplicationName',
        'application_version' => 'getApplicationVersion',
        'application_build_number' => 'getApplicationBuildNumber',
        'install_referrer' => 'getInstallReferrer',
        'package' => 'getPackage',
        'os' => 'getOs',
        'apple_search_ads_attributes' => 'getAppleSearchAdsAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const OS_UNKNOWN = 'Unknown';
    const OS_IOS = 'IOS';
    const OS_ANDROID = 'Android';
    const OS_WINDOWS_PHONE = 'WindowsPhone';
    const OS_MOBILE_WEB = 'MobileWeb';
    const OS_UNITY_IOS = 'UnityIOS';
    const OS_UNITY_ANDROID = 'UnityAndroid';
    const OS_DESKTOP = 'Desktop';
    const OS_TVOS = 'TVOS';
    const OS_ROKU = 'Roku';
    const OS_OUT_OF_BAND = 'OutOfBand';
    const OS_ALEXA = 'Alexa';
    const OS_SMART_TV = 'SmartTV';
    const OS_FIRE_TV = 'FireTV';
    const OS_XBOX = 'Xbox';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOsAllowableValues()
    {
        return [
            self::OS_UNKNOWN,
            self::OS_IOS,
            self::OS_ANDROID,
            self::OS_WINDOWS_PHONE,
            self::OS_MOBILE_WEB,
            self::OS_UNITY_IOS,
            self::OS_UNITY_ANDROID,
            self::OS_DESKTOP,
            self::OS_TVOS,
            self::OS_ROKU,
            self::OS_OUT_OF_BAND,
            self::OS_ALEXA,
            self::OS_SMART_TV,
            self::OS_FIRE_TV,
            self::OS_XBOX,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['application_name'] = isset($data['application_name']) ? $data['application_name'] : null;
        $this->container['application_version'] = isset($data['application_version']) ? $data['application_version'] : null;
        $this->container['application_build_number'] = isset($data['application_build_number']) ? $data['application_build_number'] : null;
        $this->container['install_referrer'] = isset($data['install_referrer']) ? $data['install_referrer'] : null;
        $this->container['package'] = isset($data['package']) ? $data['package'] : null;
        $this->container['os'] = isset($data['os']) ? $data['os'] : 'Unknown';
        $this->container['apple_search_ads_attributes'] = isset($data['apple_search_ads_attributes']) ? $data['apple_search_ads_attributes'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getOsAllowableValues();
        if (!is_null($this->container['os']) && !in_array($this->container['os'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'os', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application_name
     *
     * @return string|null
     */
    public function getApplicationName()
    {
        return $this->container['application_name'];
    }

    /**
     * Sets application_name
     *
     * @param string|null $application_name application_name
     *
     * @return $this
     */
    public function setApplicationName($application_name)
    {
        $this->container['application_name'] = $application_name;

        return $this;
    }

    /**
     * Gets application_version
     *
     * @return string|null
     */
    public function getApplicationVersion()
    {
        return $this->container['application_version'];
    }

    /**
     * Sets application_version
     *
     * @param string|null $application_version application_version
     *
     * @return $this
     */
    public function setApplicationVersion($application_version)
    {
        $this->container['application_version'] = $application_version;

        return $this;
    }

    /**
     * Gets application_build_number
     *
     * @return string|null
     */
    public function getApplicationBuildNumber()
    {
        return $this->container['application_build_number'];
    }

    /**
     * Sets application_build_number
     *
     * @param string|null $application_build_number application_build_number
     *
     * @return $this
     */
    public function setApplicationBuildNumber($application_build_number)
    {
        $this->container['application_build_number'] = $application_build_number;

        return $this;
    }

    /**
     * Gets install_referrer
     *
     * @return string|null
     */
    public function getInstallReferrer()
    {
        return $this->container['install_referrer'];
    }

    /**
     * Sets install_referrer
     *
     * @param string|null $install_referrer install_referrer
     *
     * @return $this
     */
    public function setInstallReferrer($install_referrer)
    {
        $this->container['install_referrer'] = $install_referrer;

        return $this;
    }

    /**
     * Gets package
     *
     * @return string|null
     */
    public function getPackage()
    {
        return $this->container['package'];
    }

    /**
     * Sets package
     *
     * @param string|null $package package
     *
     * @return $this
     */
    public function setPackage($package)
    {
        $this->container['package'] = $package;

        return $this;
    }

    /**
     * Gets os
     *
     * @return string|null
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     *
     * @param string|null $os os
     *
     * @return $this
     */
    public function setOs($os)
    {
        $allowedValues = $this->getOsAllowableValues();
        if (!is_null($os) && !in_array($os, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'os', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets apple_search_ads_attributes
     *
     * @return map[string,map[string,string]]|null
     */
    public function getAppleSearchAdsAttributes()
    {
        return $this->container['apple_search_ads_attributes'];
    }

    /**
     * Sets apple_search_ads_attributes
     *
     * @param map[string,map[string,string]]|null $apple_search_ads_attributes apple_search_ads_attributes
     *
     * @return $this
     */
    public function setAppleSearchAdsAttributes($apple_search_ads_attributes)
    {
        $this->container['apple_search_ads_attributes'] = $apple_search_ads_attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


