<?php
/**
 * ApplicationStateTransitionEventDataAllOf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApplicationStateTransitionEventDataAllOf Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationStateTransitionEventDataAllOf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApplicationStateTransitionEventData_allOf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'successfully_closed' => 'bool',
        'is_first_run' => 'bool',
        'is_upgrade' => 'bool',
        'push_notification_payload' => 'string',
        'launch_referral' => 'string',
        'application_transition_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'successfully_closed' => null,
        'is_first_run' => null,
        'is_upgrade' => null,
        'push_notification_payload' => null,
        'launch_referral' => null,
        'application_transition_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successfully_closed' => 'successfully_closed',
        'is_first_run' => 'is_first_run',
        'is_upgrade' => 'is_upgrade',
        'push_notification_payload' => 'push_notification_payload',
        'launch_referral' => 'launch_referral',
        'application_transition_type' => 'application_transition_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successfully_closed' => 'setSuccessfullyClosed',
        'is_first_run' => 'setIsFirstRun',
        'is_upgrade' => 'setIsUpgrade',
        'push_notification_payload' => 'setPushNotificationPayload',
        'launch_referral' => 'setLaunchReferral',
        'application_transition_type' => 'setApplicationTransitionType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successfully_closed' => 'getSuccessfullyClosed',
        'is_first_run' => 'getIsFirstRun',
        'is_upgrade' => 'getIsUpgrade',
        'push_notification_payload' => 'getPushNotificationPayload',
        'launch_referral' => 'getLaunchReferral',
        'application_transition_type' => 'getApplicationTransitionType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const APPLICATION_TRANSITION_TYPE_INITIALIZED = 'application_initialized';
    const APPLICATION_TRANSITION_TYPE__EXIT = 'application_exit';
    const APPLICATION_TRANSITION_TYPE_BACKGROUND = 'application_background';
    const APPLICATION_TRANSITION_TYPE_FOREGROUND = 'application_foreground';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplicationTransitionTypeAllowableValues()
    {
        return [
            self::APPLICATION_TRANSITION_TYPE_INITIALIZED,
            self::APPLICATION_TRANSITION_TYPE__EXIT,
            self::APPLICATION_TRANSITION_TYPE_BACKGROUND,
            self::APPLICATION_TRANSITION_TYPE_FOREGROUND,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successfully_closed'] = isset($data['successfully_closed']) ? $data['successfully_closed'] : null;
        $this->container['is_first_run'] = isset($data['is_first_run']) ? $data['is_first_run'] : null;
        $this->container['is_upgrade'] = isset($data['is_upgrade']) ? $data['is_upgrade'] : null;
        $this->container['push_notification_payload'] = isset($data['push_notification_payload']) ? $data['push_notification_payload'] : null;
        $this->container['launch_referral'] = isset($data['launch_referral']) ? $data['launch_referral'] : null;
        $this->container['application_transition_type'] = isset($data['application_transition_type']) ? $data['application_transition_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_first_run'] === null) {
            $invalidProperties[] = "'is_first_run' can't be null";
        }
        if ($this->container['is_upgrade'] === null) {
            $invalidProperties[] = "'is_upgrade' can't be null";
        }
        if ($this->container['application_transition_type'] === null) {
            $invalidProperties[] = "'application_transition_type' can't be null";
        }
        $allowedValues = $this->getApplicationTransitionTypeAllowableValues();
        if (!is_null($this->container['application_transition_type']) && !in_array($this->container['application_transition_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'application_transition_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets successfully_closed
     *
     * @return bool|null
     */
    public function getSuccessfullyClosed()
    {
        return $this->container['successfully_closed'];
    }

    /**
     * Sets successfully_closed
     *
     * @param bool|null $successfully_closed successfully_closed
     *
     * @return $this
     */
    public function setSuccessfullyClosed($successfully_closed)
    {
        $this->container['successfully_closed'] = $successfully_closed;

        return $this;
    }

    /**
     * Gets is_first_run
     *
     * @return bool
     */
    public function getIsFirstRun()
    {
        return $this->container['is_first_run'];
    }

    /**
     * Sets is_first_run
     *
     * @param bool $is_first_run is_first_run
     *
     * @return $this
     */
    public function setIsFirstRun($is_first_run)
    {
        $this->container['is_first_run'] = $is_first_run;

        return $this;
    }

    /**
     * Gets is_upgrade
     *
     * @return bool
     */
    public function getIsUpgrade()
    {
        return $this->container['is_upgrade'];
    }

    /**
     * Sets is_upgrade
     *
     * @param bool $is_upgrade is_upgrade
     *
     * @return $this
     */
    public function setIsUpgrade($is_upgrade)
    {
        $this->container['is_upgrade'] = $is_upgrade;

        return $this;
    }

    /**
     * Gets push_notification_payload
     *
     * @return string|null
     */
    public function getPushNotificationPayload()
    {
        return $this->container['push_notification_payload'];
    }

    /**
     * Sets push_notification_payload
     *
     * @param string|null $push_notification_payload push_notification_payload
     *
     * @return $this
     */
    public function setPushNotificationPayload($push_notification_payload)
    {
        $this->container['push_notification_payload'] = $push_notification_payload;

        return $this;
    }

    /**
     * Gets launch_referral
     *
     * @return string|null
     */
    public function getLaunchReferral()
    {
        return $this->container['launch_referral'];
    }

    /**
     * Sets launch_referral
     *
     * @param string|null $launch_referral launch_referral
     *
     * @return $this
     */
    public function setLaunchReferral($launch_referral)
    {
        $this->container['launch_referral'] = $launch_referral;

        return $this;
    }

    /**
     * Gets application_transition_type
     *
     * @return string
     */
    public function getApplicationTransitionType()
    {
        return $this->container['application_transition_type'];
    }

    /**
     * Sets application_transition_type
     *
     * @param string $application_transition_type application_transition_type
     *
     * @return $this
     */
    public function setApplicationTransitionType($application_transition_type)
    {
        $allowedValues = $this->getApplicationTransitionTypeAllowableValues();
        if (!in_array($application_transition_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'application_transition_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['application_transition_type'] = $application_transition_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


