<?php
/**
 * Batch
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Batch Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Batch implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Batch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'source_request_id' => 'string',
        'events' => '\OpenAPI\Client\Model\BaseEvent[]',
        'device_info' => '\OpenAPI\Client\Model\DeviceInformation',
        'application_info' => '\OpenAPI\Client\Model\ApplicationInformation',
        'user_attributes' => 'map[string,object]',
        'deleted_user_attributes' => 'string[]',
        'user_identities' => '\OpenAPI\Client\Model\BatchUserIdentities',
        'environment' => 'string',
        'api_key' => 'string',
        'api_keys' => 'string[]',
        'ip' => 'string',
        'integration_attributes' => 'map[string,map[string,string]]',
        'partner_identity' => 'string',
        'source_info' => '\OpenAPI\Client\Model\SourceInformation',
        'mp_deviceid' => 'string',
        'attribution_info' => '\OpenAPI\Client\Model\AttributionInfo',
        'timestamp_unixtime_ms' => 'int',
        'batch_id' => 'int',
        'mpid' => 'int',
        'sdk_version' => 'string',
        'consent_state' => '\OpenAPI\Client\Model\ConsentState',
        'job_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'source_request_id' => null,
        'events' => null,
        'device_info' => null,
        'application_info' => null,
        'user_attributes' => null,
        'deleted_user_attributes' => null,
        'user_identities' => null,
        'environment' => null,
        'api_key' => null,
        'api_keys' => null,
        'ip' => null,
        'integration_attributes' => null,
        'partner_identity' => null,
        'source_info' => null,
        'mp_deviceid' => null,
        'attribution_info' => null,
        'timestamp_unixtime_ms' => 'int64',
        'batch_id' => 'int64',
        'mpid' => 'int64',
        'sdk_version' => null,
        'consent_state' => null,
        'job_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'source_request_id' => 'source_request_id',
        'events' => 'events',
        'device_info' => 'device_info',
        'application_info' => 'application_info',
        'user_attributes' => 'user_attributes',
        'deleted_user_attributes' => 'deleted_user_attributes',
        'user_identities' => 'user_identities',
        'environment' => 'environment',
        'api_key' => 'api_key',
        'api_keys' => 'api_keys',
        'ip' => 'ip',
        'integration_attributes' => 'integration_attributes',
        'partner_identity' => 'partner_identity',
        'source_info' => 'source_info',
        'mp_deviceid' => 'mp_deviceid',
        'attribution_info' => 'attribution_info',
        'timestamp_unixtime_ms' => 'timestamp_unixtime_ms',
        'batch_id' => 'batch_id',
        'mpid' => 'mpid',
        'sdk_version' => 'sdk_version',
        'consent_state' => 'consent_state',
        'job_id' => 'job_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'source_request_id' => 'setSourceRequestId',
        'events' => 'setEvents',
        'device_info' => 'setDeviceInfo',
        'application_info' => 'setApplicationInfo',
        'user_attributes' => 'setUserAttributes',
        'deleted_user_attributes' => 'setDeletedUserAttributes',
        'user_identities' => 'setUserIdentities',
        'environment' => 'setEnvironment',
        'api_key' => 'setApiKey',
        'api_keys' => 'setApiKeys',
        'ip' => 'setIp',
        'integration_attributes' => 'setIntegrationAttributes',
        'partner_identity' => 'setPartnerIdentity',
        'source_info' => 'setSourceInfo',
        'mp_deviceid' => 'setMpDeviceid',
        'attribution_info' => 'setAttributionInfo',
        'timestamp_unixtime_ms' => 'setTimestampUnixtimeMs',
        'batch_id' => 'setBatchId',
        'mpid' => 'setMpid',
        'sdk_version' => 'setSdkVersion',
        'consent_state' => 'setConsentState',
        'job_id' => 'setJobId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'source_request_id' => 'getSourceRequestId',
        'events' => 'getEvents',
        'device_info' => 'getDeviceInfo',
        'application_info' => 'getApplicationInfo',
        'user_attributes' => 'getUserAttributes',
        'deleted_user_attributes' => 'getDeletedUserAttributes',
        'user_identities' => 'getUserIdentities',
        'environment' => 'getEnvironment',
        'api_key' => 'getApiKey',
        'api_keys' => 'getApiKeys',
        'ip' => 'getIp',
        'integration_attributes' => 'getIntegrationAttributes',
        'partner_identity' => 'getPartnerIdentity',
        'source_info' => 'getSourceInfo',
        'mp_deviceid' => 'getMpDeviceid',
        'attribution_info' => 'getAttributionInfo',
        'timestamp_unixtime_ms' => 'getTimestampUnixtimeMs',
        'batch_id' => 'getBatchId',
        'mpid' => 'getMpid',
        'sdk_version' => 'getSdkVersion',
        'consent_state' => 'getConsentState',
        'job_id' => 'getJobId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const ENVIRONMENT_UNKNOWN = 'unknown';
    const ENVIRONMENT_DEVELOPMENT = 'development';
    const ENVIRONMENT_PRODUCTION = 'production';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnvironmentAllowableValues()
    {
        return [
            self::ENVIRONMENT_UNKNOWN,
            self::ENVIRONMENT_DEVELOPMENT,
            self::ENVIRONMENT_PRODUCTION,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['source_request_id'] = isset($data['source_request_id']) ? $data['source_request_id'] : null;
        $this->container['events'] = isset($data['events']) ? $data['events'] : null;
        $this->container['device_info'] = isset($data['device_info']) ? $data['device_info'] : null;
        $this->container['application_info'] = isset($data['application_info']) ? $data['application_info'] : null;
        $this->container['user_attributes'] = isset($data['user_attributes']) ? $data['user_attributes'] : null;
        $this->container['deleted_user_attributes'] = isset($data['deleted_user_attributes']) ? $data['deleted_user_attributes'] : null;
        $this->container['user_identities'] = isset($data['user_identities']) ? $data['user_identities'] : null;
        $this->container['environment'] = isset($data['environment']) ? $data['environment'] : 'production';
        $this->container['api_key'] = isset($data['api_key']) ? $data['api_key'] : null;
        $this->container['api_keys'] = isset($data['api_keys']) ? $data['api_keys'] : null;
        $this->container['ip'] = isset($data['ip']) ? $data['ip'] : null;
        $this->container['integration_attributes'] = isset($data['integration_attributes']) ? $data['integration_attributes'] : null;
        $this->container['partner_identity'] = isset($data['partner_identity']) ? $data['partner_identity'] : null;
        $this->container['source_info'] = isset($data['source_info']) ? $data['source_info'] : null;
        $this->container['mp_deviceid'] = isset($data['mp_deviceid']) ? $data['mp_deviceid'] : null;
        $this->container['attribution_info'] = isset($data['attribution_info']) ? $data['attribution_info'] : null;
        $this->container['timestamp_unixtime_ms'] = isset($data['timestamp_unixtime_ms']) ? $data['timestamp_unixtime_ms'] : null;
        $this->container['batch_id'] = isset($data['batch_id']) ? $data['batch_id'] : null;
        $this->container['mpid'] = isset($data['mpid']) ? $data['mpid'] : null;
        $this->container['sdk_version'] = isset($data['sdk_version']) ? $data['sdk_version'] : null;
        $this->container['consent_state'] = isset($data['consent_state']) ? $data['consent_state'] : null;
        $this->container['job_id'] = isset($data['job_id']) ? $data['job_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['environment'] === null) {
            $invalidProperties[] = "'environment' can't be null";
        }
        $allowedValues = $this->getEnvironmentAllowableValues();
        if (!is_null($this->container['environment']) && !in_array($this->container['environment'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'environment', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets source_request_id
     *
     * @return string|null
     */
    public function getSourceRequestId()
    {
        return $this->container['source_request_id'];
    }

    /**
     * Sets source_request_id
     *
     * @param string|null $source_request_id source_request_id
     *
     * @return $this
     */
    public function setSourceRequestId($source_request_id)
    {
        $this->container['source_request_id'] = $source_request_id;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \OpenAPI\Client\Model\BaseEvent[]|null
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \OpenAPI\Client\Model\BaseEvent[]|null $events Provide a list of event objects - such as CustomEvent, ScreenViewEvent, or CommerceEvent
     *
     * @return $this
     */
    public function setEvents($events)
    {
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets device_info
     *
     * @return \OpenAPI\Client\Model\DeviceInformation|null
     */
    public function getDeviceInfo()
    {
        return $this->container['device_info'];
    }

    /**
     * Sets device_info
     *
     * @param \OpenAPI\Client\Model\DeviceInformation|null $device_info device_info
     *
     * @return $this
     */
    public function setDeviceInfo($device_info)
    {
        $this->container['device_info'] = $device_info;

        return $this;
    }

    /**
     * Gets application_info
     *
     * @return \OpenAPI\Client\Model\ApplicationInformation|null
     */
    public function getApplicationInfo()
    {
        return $this->container['application_info'];
    }

    /**
     * Sets application_info
     *
     * @param \OpenAPI\Client\Model\ApplicationInformation|null $application_info application_info
     *
     * @return $this
     */
    public function setApplicationInfo($application_info)
    {
        $this->container['application_info'] = $application_info;

        return $this;
    }

    /**
     * Gets user_attributes
     *
     * @return map[string,object]|null
     */
    public function getUserAttributes()
    {
        return $this->container['user_attributes'];
    }

    /**
     * Sets user_attributes
     *
     * @param map[string,object]|null $user_attributes user_attributes
     *
     * @return $this
     */
    public function setUserAttributes($user_attributes)
    {
        $this->container['user_attributes'] = $user_attributes;

        return $this;
    }

    /**
     * Gets deleted_user_attributes
     *
     * @return string[]|null
     */
    public function getDeletedUserAttributes()
    {
        return $this->container['deleted_user_attributes'];
    }

    /**
     * Sets deleted_user_attributes
     *
     * @param string[]|null $deleted_user_attributes deleted_user_attributes
     *
     * @return $this
     */
    public function setDeletedUserAttributes($deleted_user_attributes)
    {
        $this->container['deleted_user_attributes'] = $deleted_user_attributes;

        return $this;
    }

    /**
     * Gets user_identities
     *
     * @return \OpenAPI\Client\Model\BatchUserIdentities|null
     */
    public function getUserIdentities()
    {
        return $this->container['user_identities'];
    }

    /**
     * Sets user_identities
     *
     * @param \OpenAPI\Client\Model\BatchUserIdentities|null $user_identities user_identities
     *
     * @return $this
     */
    public function setUserIdentities($user_identities)
    {
        $this->container['user_identities'] = $user_identities;

        return $this;
    }

    /**
     * Gets environment
     *
     * @return string
     */
    public function getEnvironment()
    {
        return $this->container['environment'];
    }

    /**
     * Sets environment
     *
     * @param string $environment environment
     *
     * @return $this
     */
    public function setEnvironment($environment)
    {
        $allowedValues = $this->getEnvironmentAllowableValues();
        if (!in_array($environment, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'environment', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['environment'] = $environment;

        return $this;
    }

    /**
     * Gets api_key
     *
     * @return string|null
     */
    public function getApiKey()
    {
        return $this->container['api_key'];
    }

    /**
     * Sets api_key
     *
     * @param string|null $api_key api_key
     *
     * @return $this
     */
    public function setApiKey($api_key)
    {
        $this->container['api_key'] = $api_key;

        return $this;
    }

    /**
     * Gets api_keys
     *
     * @return string[]|null
     */
    public function getApiKeys()
    {
        return $this->container['api_keys'];
    }

    /**
     * Sets api_keys
     *
     * @param string[]|null $api_keys api_keys
     *
     * @return $this
     */
    public function setApiKeys($api_keys)
    {
        $this->container['api_keys'] = $api_keys;

        return $this;
    }

    /**
     * Gets ip
     *
     * @return string|null
     */
    public function getIp()
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string|null $ip ip
     *
     * @return $this
     */
    public function setIp($ip)
    {
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets integration_attributes
     *
     * @return map[string,map[string,string]]|null
     */
    public function getIntegrationAttributes()
    {
        return $this->container['integration_attributes'];
    }

    /**
     * Sets integration_attributes
     *
     * @param map[string,map[string,string]]|null $integration_attributes integration_attributes
     *
     * @return $this
     */
    public function setIntegrationAttributes($integration_attributes)
    {
        $this->container['integration_attributes'] = $integration_attributes;

        return $this;
    }

    /**
     * Gets partner_identity
     *
     * @return string|null
     */
    public function getPartnerIdentity()
    {
        return $this->container['partner_identity'];
    }

    /**
     * Sets partner_identity
     *
     * @param string|null $partner_identity partner_identity
     *
     * @return $this
     */
    public function setPartnerIdentity($partner_identity)
    {
        $this->container['partner_identity'] = $partner_identity;

        return $this;
    }

    /**
     * Gets source_info
     *
     * @return \OpenAPI\Client\Model\SourceInformation|null
     */
    public function getSourceInfo()
    {
        return $this->container['source_info'];
    }

    /**
     * Sets source_info
     *
     * @param \OpenAPI\Client\Model\SourceInformation|null $source_info source_info
     *
     * @return $this
     */
    public function setSourceInfo($source_info)
    {
        $this->container['source_info'] = $source_info;

        return $this;
    }

    /**
     * Gets mp_deviceid
     *
     * @return string|null
     */
    public function getMpDeviceid()
    {
        return $this->container['mp_deviceid'];
    }

    /**
     * Sets mp_deviceid
     *
     * @param string|null $mp_deviceid mp_deviceid
     *
     * @return $this
     */
    public function setMpDeviceid($mp_deviceid)
    {
        $this->container['mp_deviceid'] = $mp_deviceid;

        return $this;
    }

    /**
     * Gets attribution_info
     *
     * @return \OpenAPI\Client\Model\AttributionInfo|null
     */
    public function getAttributionInfo()
    {
        return $this->container['attribution_info'];
    }

    /**
     * Sets attribution_info
     *
     * @param \OpenAPI\Client\Model\AttributionInfo|null $attribution_info attribution_info
     *
     * @return $this
     */
    public function setAttributionInfo($attribution_info)
    {
        $this->container['attribution_info'] = $attribution_info;

        return $this;
    }

    /**
     * Gets timestamp_unixtime_ms
     *
     * @return int|null
     */
    public function getTimestampUnixtimeMs()
    {
        return $this->container['timestamp_unixtime_ms'];
    }

    /**
     * Sets timestamp_unixtime_ms
     *
     * @param int|null $timestamp_unixtime_ms timestamp_unixtime_ms
     *
     * @return $this
     */
    public function setTimestampUnixtimeMs($timestamp_unixtime_ms)
    {
        $this->container['timestamp_unixtime_ms'] = $timestamp_unixtime_ms;

        return $this;
    }

    /**
     * Gets batch_id
     *
     * @return int|null
     */
    public function getBatchId()
    {
        return $this->container['batch_id'];
    }

    /**
     * Sets batch_id
     *
     * @param int|null $batch_id batch_id
     *
     * @return $this
     */
    public function setBatchId($batch_id)
    {
        $this->container['batch_id'] = $batch_id;

        return $this;
    }

    /**
     * Gets mpid
     *
     * @return int|null
     */
    public function getMpid()
    {
        return $this->container['mpid'];
    }

    /**
     * Sets mpid
     *
     * @param int|null $mpid mpid
     *
     * @return $this
     */
    public function setMpid($mpid)
    {
        $this->container['mpid'] = $mpid;

        return $this;
    }

    /**
     * Gets sdk_version
     *
     * @return string|null
     */
    public function getSdkVersion()
    {
        return $this->container['sdk_version'];
    }

    /**
     * Sets sdk_version
     *
     * @param string|null $sdk_version sdk_version
     *
     * @return $this
     */
    public function setSdkVersion($sdk_version)
    {
        $this->container['sdk_version'] = $sdk_version;

        return $this;
    }

    /**
     * Gets consent_state
     *
     * @return \OpenAPI\Client\Model\ConsentState|null
     */
    public function getConsentState()
    {
        return $this->container['consent_state'];
    }

    /**
     * Sets consent_state
     *
     * @param \OpenAPI\Client\Model\ConsentState|null $consent_state consent_state
     *
     * @return $this
     */
    public function setConsentState($consent_state)
    {
        $this->container['consent_state'] = $consent_state;

        return $this;
    }

    /**
     * Gets job_id
     *
     * @return string|null
     */
    public function getJobId()
    {
        return $this->container['job_id'];
    }

    /**
     * Sets job_id
     *
     * @param string|null $job_id job_id
     *
     * @return $this
     */
    public function setJobId($job_id)
    {
        $this->container['job_id'] = $job_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


