<?php
/**
 * BatchUserIdentities
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BatchUserIdentities Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchUserIdentities implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Batch_user_identities';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'other' => 'string',
        'customer_id' => 'string',
        'facebook' => 'string',
        'twitter' => 'string',
        'google' => 'string',
        'microsoft' => 'string',
        'yahoo' => 'string',
        'email' => 'string',
        'alias' => 'string',
        'facebook_custom_audience_id' => 'string',
        'other_id_2' => 'string',
        'other_id_3' => 'string',
        'other_id_4' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'other' => null,
        'customer_id' => null,
        'facebook' => null,
        'twitter' => null,
        'google' => null,
        'microsoft' => null,
        'yahoo' => null,
        'email' => null,
        'alias' => null,
        'facebook_custom_audience_id' => null,
        'other_id_2' => null,
        'other_id_3' => null,
        'other_id_4' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'other' => 'other',
        'customer_id' => 'customer_id',
        'facebook' => 'facebook',
        'twitter' => 'twitter',
        'google' => 'google',
        'microsoft' => 'microsoft',
        'yahoo' => 'yahoo',
        'email' => 'email',
        'alias' => 'alias',
        'facebook_custom_audience_id' => 'facebook_custom_audience_id',
        'other_id_2' => 'other_id_2',
        'other_id_3' => 'other_id_3',
        'other_id_4' => 'other_id_4'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'other' => 'setOther',
        'customer_id' => 'setCustomerId',
        'facebook' => 'setFacebook',
        'twitter' => 'setTwitter',
        'google' => 'setGoogle',
        'microsoft' => 'setMicrosoft',
        'yahoo' => 'setYahoo',
        'email' => 'setEmail',
        'alias' => 'setAlias',
        'facebook_custom_audience_id' => 'setFacebookCustomAudienceId',
        'other_id_2' => 'setOtherId2',
        'other_id_3' => 'setOtherId3',
        'other_id_4' => 'setOtherId4'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'other' => 'getOther',
        'customer_id' => 'getCustomerId',
        'facebook' => 'getFacebook',
        'twitter' => 'getTwitter',
        'google' => 'getGoogle',
        'microsoft' => 'getMicrosoft',
        'yahoo' => 'getYahoo',
        'email' => 'getEmail',
        'alias' => 'getAlias',
        'facebook_custom_audience_id' => 'getFacebookCustomAudienceId',
        'other_id_2' => 'getOtherId2',
        'other_id_3' => 'getOtherId3',
        'other_id_4' => 'getOtherId4'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['other'] = isset($data['other']) ? $data['other'] : null;
        $this->container['customer_id'] = isset($data['customer_id']) ? $data['customer_id'] : null;
        $this->container['facebook'] = isset($data['facebook']) ? $data['facebook'] : null;
        $this->container['twitter'] = isset($data['twitter']) ? $data['twitter'] : null;
        $this->container['google'] = isset($data['google']) ? $data['google'] : null;
        $this->container['microsoft'] = isset($data['microsoft']) ? $data['microsoft'] : null;
        $this->container['yahoo'] = isset($data['yahoo']) ? $data['yahoo'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['alias'] = isset($data['alias']) ? $data['alias'] : null;
        $this->container['facebook_custom_audience_id'] = isset($data['facebook_custom_audience_id']) ? $data['facebook_custom_audience_id'] : null;
        $this->container['other_id_2'] = isset($data['other_id_2']) ? $data['other_id_2'] : null;
        $this->container['other_id_3'] = isset($data['other_id_3']) ? $data['other_id_3'] : null;
        $this->container['other_id_4'] = isset($data['other_id_4']) ? $data['other_id_4'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets other
     *
     * @return string|null
     */
    public function getOther()
    {
        return $this->container['other'];
    }

    /**
     * Sets other
     *
     * @param string|null $other other
     *
     * @return $this
     */
    public function setOther($other)
    {
        $this->container['other'] = $other;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id customer_id
     *
     * @return $this
     */
    public function setCustomerId($customer_id)
    {
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets facebook
     *
     * @return string|null
     */
    public function getFacebook()
    {
        return $this->container['facebook'];
    }

    /**
     * Sets facebook
     *
     * @param string|null $facebook facebook
     *
     * @return $this
     */
    public function setFacebook($facebook)
    {
        $this->container['facebook'] = $facebook;

        return $this;
    }

    /**
     * Gets twitter
     *
     * @return string|null
     */
    public function getTwitter()
    {
        return $this->container['twitter'];
    }

    /**
     * Sets twitter
     *
     * @param string|null $twitter twitter
     *
     * @return $this
     */
    public function setTwitter($twitter)
    {
        $this->container['twitter'] = $twitter;

        return $this;
    }

    /**
     * Gets google
     *
     * @return string|null
     */
    public function getGoogle()
    {
        return $this->container['google'];
    }

    /**
     * Sets google
     *
     * @param string|null $google google
     *
     * @return $this
     */
    public function setGoogle($google)
    {
        $this->container['google'] = $google;

        return $this;
    }

    /**
     * Gets microsoft
     *
     * @return string|null
     */
    public function getMicrosoft()
    {
        return $this->container['microsoft'];
    }

    /**
     * Sets microsoft
     *
     * @param string|null $microsoft microsoft
     *
     * @return $this
     */
    public function setMicrosoft($microsoft)
    {
        $this->container['microsoft'] = $microsoft;

        return $this;
    }

    /**
     * Gets yahoo
     *
     * @return string|null
     */
    public function getYahoo()
    {
        return $this->container['yahoo'];
    }

    /**
     * Sets yahoo
     *
     * @param string|null $yahoo yahoo
     *
     * @return $this
     */
    public function setYahoo($yahoo)
    {
        $this->container['yahoo'] = $yahoo;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets alias
     *
     * @return string|null
     */
    public function getAlias()
    {
        return $this->container['alias'];
    }

    /**
     * Sets alias
     *
     * @param string|null $alias alias
     *
     * @return $this
     */
    public function setAlias($alias)
    {
        $this->container['alias'] = $alias;

        return $this;
    }

    /**
     * Gets facebook_custom_audience_id
     *
     * @return string|null
     */
    public function getFacebookCustomAudienceId()
    {
        return $this->container['facebook_custom_audience_id'];
    }

    /**
     * Sets facebook_custom_audience_id
     *
     * @param string|null $facebook_custom_audience_id facebook_custom_audience_id
     *
     * @return $this
     */
    public function setFacebookCustomAudienceId($facebook_custom_audience_id)
    {
        $this->container['facebook_custom_audience_id'] = $facebook_custom_audience_id;

        return $this;
    }

    /**
     * Gets other_id_2
     *
     * @return string|null
     */
    public function getOtherId2()
    {
        return $this->container['other_id_2'];
    }

    /**
     * Sets other_id_2
     *
     * @param string|null $other_id_2 other_id_2
     *
     * @return $this
     */
    public function setOtherId2($other_id_2)
    {
        $this->container['other_id_2'] = $other_id_2;

        return $this;
    }

    /**
     * Gets other_id_3
     *
     * @return string|null
     */
    public function getOtherId3()
    {
        return $this->container['other_id_3'];
    }

    /**
     * Sets other_id_3
     *
     * @param string|null $other_id_3 other_id_3
     *
     * @return $this
     */
    public function setOtherId3($other_id_3)
    {
        $this->container['other_id_3'] = $other_id_3;

        return $this;
    }

    /**
     * Gets other_id_4
     *
     * @return string|null
     */
    public function getOtherId4()
    {
        return $this->container['other_id_4'];
    }

    /**
     * Sets other_id_4
     *
     * @param string|null $other_id_4 other_id_4
     *
     * @return $this
     */
    public function setOtherId4($other_id_4)
    {
        $this->container['other_id_4'] = $other_id_4;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


