<?php
/**
 * CustomEventData
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomEventData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomEventData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomEventData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'timestamp_unixtime_ms' => 'int',
        'event_id' => 'int',
        'source_message_id' => 'string',
        'session_id' => 'int',
        'session_uuid' => 'string',
        'session_start_unixtime_ms' => 'int',
        'event_start_unixtime_ms' => 'int',
        'custom_attributes' => 'map[string,string]',
        'location' => '\OpenAPI\Client\Model\GeoLocation',
        'device_current_state' => '\OpenAPI\Client\Model\DeviceCurrentState',
        'is_goal_defined' => 'bool',
        'lifetime_value_change' => 'bool',
        'lifetime_value_attribute_name' => 'string',
        'data_connection_type' => 'string',
        'event_num' => 'int',
        'view_controller' => 'string',
        'is_main_thread' => 'bool',
        'canonical_name' => 'string',
        'event_system_notification_info' => '\OpenAPI\Client\Model\EventSystemNotificationInfo',
        'custom_event_type' => 'string',
        'event_name' => 'string',
        'custom_flags' => 'map[string,string]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'timestamp_unixtime_ms' => null,
        'event_id' => 'int64',
        'source_message_id' => null,
        'session_id' => 'int64',
        'session_uuid' => null,
        'session_start_unixtime_ms' => null,
        'event_start_unixtime_ms' => null,
        'custom_attributes' => null,
        'location' => null,
        'device_current_state' => null,
        'is_goal_defined' => null,
        'lifetime_value_change' => null,
        'lifetime_value_attribute_name' => null,
        'data_connection_type' => null,
        'event_num' => null,
        'view_controller' => null,
        'is_main_thread' => null,
        'canonical_name' => null,
        'event_system_notification_info' => null,
        'custom_event_type' => null,
        'event_name' => null,
        'custom_flags' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timestamp_unixtime_ms' => 'timestamp_unixtime_ms',
        'event_id' => 'event_id',
        'source_message_id' => 'source_message_id',
        'session_id' => 'session_id',
        'session_uuid' => 'session_uuid',
        'session_start_unixtime_ms' => 'session_start_unixtime_ms',
        'event_start_unixtime_ms' => 'event_start_unixtime_ms',
        'custom_attributes' => 'custom_attributes',
        'location' => 'location',
        'device_current_state' => 'device_current_state',
        'is_goal_defined' => 'is_goal_defined',
        'lifetime_value_change' => 'lifetime_value_change',
        'lifetime_value_attribute_name' => 'lifetime_value_attribute_name',
        'data_connection_type' => 'data_connection_type',
        'event_num' => 'event_num',
        'view_controller' => 'view_controller',
        'is_main_thread' => 'is_main_thread',
        'canonical_name' => 'canonical_name',
        'event_system_notification_info' => 'event_system_notification_info',
        'custom_event_type' => 'custom_event_type',
        'event_name' => 'event_name',
        'custom_flags' => 'custom_flags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timestamp_unixtime_ms' => 'setTimestampUnixtimeMs',
        'event_id' => 'setEventId',
        'source_message_id' => 'setSourceMessageId',
        'session_id' => 'setSessionId',
        'session_uuid' => 'setSessionUuid',
        'session_start_unixtime_ms' => 'setSessionStartUnixtimeMs',
        'event_start_unixtime_ms' => 'setEventStartUnixtimeMs',
        'custom_attributes' => 'setCustomAttributes',
        'location' => 'setLocation',
        'device_current_state' => 'setDeviceCurrentState',
        'is_goal_defined' => 'setIsGoalDefined',
        'lifetime_value_change' => 'setLifetimeValueChange',
        'lifetime_value_attribute_name' => 'setLifetimeValueAttributeName',
        'data_connection_type' => 'setDataConnectionType',
        'event_num' => 'setEventNum',
        'view_controller' => 'setViewController',
        'is_main_thread' => 'setIsMainThread',
        'canonical_name' => 'setCanonicalName',
        'event_system_notification_info' => 'setEventSystemNotificationInfo',
        'custom_event_type' => 'setCustomEventType',
        'event_name' => 'setEventName',
        'custom_flags' => 'setCustomFlags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timestamp_unixtime_ms' => 'getTimestampUnixtimeMs',
        'event_id' => 'getEventId',
        'source_message_id' => 'getSourceMessageId',
        'session_id' => 'getSessionId',
        'session_uuid' => 'getSessionUuid',
        'session_start_unixtime_ms' => 'getSessionStartUnixtimeMs',
        'event_start_unixtime_ms' => 'getEventStartUnixtimeMs',
        'custom_attributes' => 'getCustomAttributes',
        'location' => 'getLocation',
        'device_current_state' => 'getDeviceCurrentState',
        'is_goal_defined' => 'getIsGoalDefined',
        'lifetime_value_change' => 'getLifetimeValueChange',
        'lifetime_value_attribute_name' => 'getLifetimeValueAttributeName',
        'data_connection_type' => 'getDataConnectionType',
        'event_num' => 'getEventNum',
        'view_controller' => 'getViewController',
        'is_main_thread' => 'getIsMainThread',
        'canonical_name' => 'getCanonicalName',
        'event_system_notification_info' => 'getEventSystemNotificationInfo',
        'custom_event_type' => 'getCustomEventType',
        'event_name' => 'getEventName',
        'custom_flags' => 'getCustomFlags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const CUSTOM_EVENT_TYPE_NAVIGATION = 'navigation';
    const CUSTOM_EVENT_TYPE_LOCATION = 'location';
    const CUSTOM_EVENT_TYPE_SEARCH = 'search';
    const CUSTOM_EVENT_TYPE_TRANSACTION = 'transaction';
    const CUSTOM_EVENT_TYPE_USER_CONTENT = 'user_content';
    const CUSTOM_EVENT_TYPE_USER_PREFERENCE = 'user_preference';
    const CUSTOM_EVENT_TYPE_SOCIAL = 'social';
    const CUSTOM_EVENT_TYPE_OTHER = 'other';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCustomEventTypeAllowableValues()
    {
        return [
            self::CUSTOM_EVENT_TYPE_NAVIGATION,
            self::CUSTOM_EVENT_TYPE_LOCATION,
            self::CUSTOM_EVENT_TYPE_SEARCH,
            self::CUSTOM_EVENT_TYPE_TRANSACTION,
            self::CUSTOM_EVENT_TYPE_USER_CONTENT,
            self::CUSTOM_EVENT_TYPE_USER_PREFERENCE,
            self::CUSTOM_EVENT_TYPE_SOCIAL,
            self::CUSTOM_EVENT_TYPE_OTHER,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['timestamp_unixtime_ms'] = isset($data['timestamp_unixtime_ms']) ? $data['timestamp_unixtime_ms'] : null;
        $this->container['event_id'] = isset($data['event_id']) ? $data['event_id'] : null;
        $this->container['source_message_id'] = isset($data['source_message_id']) ? $data['source_message_id'] : null;
        $this->container['session_id'] = isset($data['session_id']) ? $data['session_id'] : null;
        $this->container['session_uuid'] = isset($data['session_uuid']) ? $data['session_uuid'] : null;
        $this->container['session_start_unixtime_ms'] = isset($data['session_start_unixtime_ms']) ? $data['session_start_unixtime_ms'] : null;
        $this->container['event_start_unixtime_ms'] = isset($data['event_start_unixtime_ms']) ? $data['event_start_unixtime_ms'] : null;
        $this->container['custom_attributes'] = isset($data['custom_attributes']) ? $data['custom_attributes'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['device_current_state'] = isset($data['device_current_state']) ? $data['device_current_state'] : null;
        $this->container['is_goal_defined'] = isset($data['is_goal_defined']) ? $data['is_goal_defined'] : null;
        $this->container['lifetime_value_change'] = isset($data['lifetime_value_change']) ? $data['lifetime_value_change'] : null;
        $this->container['lifetime_value_attribute_name'] = isset($data['lifetime_value_attribute_name']) ? $data['lifetime_value_attribute_name'] : null;
        $this->container['data_connection_type'] = isset($data['data_connection_type']) ? $data['data_connection_type'] : null;
        $this->container['event_num'] = isset($data['event_num']) ? $data['event_num'] : null;
        $this->container['view_controller'] = isset($data['view_controller']) ? $data['view_controller'] : null;
        $this->container['is_main_thread'] = isset($data['is_main_thread']) ? $data['is_main_thread'] : null;
        $this->container['canonical_name'] = isset($data['canonical_name']) ? $data['canonical_name'] : null;
        $this->container['event_system_notification_info'] = isset($data['event_system_notification_info']) ? $data['event_system_notification_info'] : null;
        $this->container['custom_event_type'] = isset($data['custom_event_type']) ? $data['custom_event_type'] : 'other';
        $this->container['event_name'] = isset($data['event_name']) ? $data['event_name'] : null;
        $this->container['custom_flags'] = isset($data['custom_flags']) ? $data['custom_flags'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['custom_event_type'] === null) {
            $invalidProperties[] = "'custom_event_type' can't be null";
        }
        $allowedValues = $this->getCustomEventTypeAllowableValues();
        if (!is_null($this->container['custom_event_type']) && !in_array($this->container['custom_event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'custom_event_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['event_name'] === null) {
            $invalidProperties[] = "'event_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timestamp_unixtime_ms
     *
     * @return int|null
     */
    public function getTimestampUnixtimeMs()
    {
        return $this->container['timestamp_unixtime_ms'];
    }

    /**
     * Sets timestamp_unixtime_ms
     *
     * @param int|null $timestamp_unixtime_ms timestamp_unixtime_ms
     *
     * @return $this
     */
    public function setTimestampUnixtimeMs($timestamp_unixtime_ms)
    {
        $this->container['timestamp_unixtime_ms'] = $timestamp_unixtime_ms;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return int|null
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param int|null $event_id event_id
     *
     * @return $this
     */
    public function setEventId($event_id)
    {
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets source_message_id
     *
     * @return string|null
     */
    public function getSourceMessageId()
    {
        return $this->container['source_message_id'];
    }

    /**
     * Sets source_message_id
     *
     * @param string|null $source_message_id source_message_id
     *
     * @return $this
     */
    public function setSourceMessageId($source_message_id)
    {
        $this->container['source_message_id'] = $source_message_id;

        return $this;
    }

    /**
     * Gets session_id
     *
     * @return int|null
     */
    public function getSessionId()
    {
        return $this->container['session_id'];
    }

    /**
     * Sets session_id
     *
     * @param int|null $session_id session_id
     *
     * @return $this
     */
    public function setSessionId($session_id)
    {
        $this->container['session_id'] = $session_id;

        return $this;
    }

    /**
     * Gets session_uuid
     *
     * @return string|null
     */
    public function getSessionUuid()
    {
        return $this->container['session_uuid'];
    }

    /**
     * Sets session_uuid
     *
     * @param string|null $session_uuid session_uuid
     *
     * @return $this
     */
    public function setSessionUuid($session_uuid)
    {
        $this->container['session_uuid'] = $session_uuid;

        return $this;
    }

    /**
     * Gets session_start_unixtime_ms
     *
     * @return int|null
     */
    public function getSessionStartUnixtimeMs()
    {
        return $this->container['session_start_unixtime_ms'];
    }

    /**
     * Sets session_start_unixtime_ms
     *
     * @param int|null $session_start_unixtime_ms session_start_unixtime_ms
     *
     * @return $this
     */
    public function setSessionStartUnixtimeMs($session_start_unixtime_ms)
    {
        $this->container['session_start_unixtime_ms'] = $session_start_unixtime_ms;

        return $this;
    }

    /**
     * Gets event_start_unixtime_ms
     *
     * @return int|null
     */
    public function getEventStartUnixtimeMs()
    {
        return $this->container['event_start_unixtime_ms'];
    }

    /**
     * Sets event_start_unixtime_ms
     *
     * @param int|null $event_start_unixtime_ms event_start_unixtime_ms
     *
     * @return $this
     */
    public function setEventStartUnixtimeMs($event_start_unixtime_ms)
    {
        $this->container['event_start_unixtime_ms'] = $event_start_unixtime_ms;

        return $this;
    }

    /**
     * Gets custom_attributes
     *
     * @return map[string,string]|null
     */
    public function getCustomAttributes()
    {
        return $this->container['custom_attributes'];
    }

    /**
     * Sets custom_attributes
     *
     * @param map[string,string]|null $custom_attributes custom_attributes
     *
     * @return $this
     */
    public function setCustomAttributes($custom_attributes)
    {
        $this->container['custom_attributes'] = $custom_attributes;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\GeoLocation|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\GeoLocation|null $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets device_current_state
     *
     * @return \OpenAPI\Client\Model\DeviceCurrentState|null
     */
    public function getDeviceCurrentState()
    {
        return $this->container['device_current_state'];
    }

    /**
     * Sets device_current_state
     *
     * @param \OpenAPI\Client\Model\DeviceCurrentState|null $device_current_state device_current_state
     *
     * @return $this
     */
    public function setDeviceCurrentState($device_current_state)
    {
        $this->container['device_current_state'] = $device_current_state;

        return $this;
    }

    /**
     * Gets is_goal_defined
     *
     * @return bool|null
     */
    public function getIsGoalDefined()
    {
        return $this->container['is_goal_defined'];
    }

    /**
     * Sets is_goal_defined
     *
     * @param bool|null $is_goal_defined is_goal_defined
     *
     * @return $this
     */
    public function setIsGoalDefined($is_goal_defined)
    {
        $this->container['is_goal_defined'] = $is_goal_defined;

        return $this;
    }

    /**
     * Gets lifetime_value_change
     *
     * @return bool|null
     */
    public function getLifetimeValueChange()
    {
        return $this->container['lifetime_value_change'];
    }

    /**
     * Sets lifetime_value_change
     *
     * @param bool|null $lifetime_value_change lifetime_value_change
     *
     * @return $this
     */
    public function setLifetimeValueChange($lifetime_value_change)
    {
        $this->container['lifetime_value_change'] = $lifetime_value_change;

        return $this;
    }

    /**
     * Gets lifetime_value_attribute_name
     *
     * @return string|null
     */
    public function getLifetimeValueAttributeName()
    {
        return $this->container['lifetime_value_attribute_name'];
    }

    /**
     * Sets lifetime_value_attribute_name
     *
     * @param string|null $lifetime_value_attribute_name lifetime_value_attribute_name
     *
     * @return $this
     */
    public function setLifetimeValueAttributeName($lifetime_value_attribute_name)
    {
        $this->container['lifetime_value_attribute_name'] = $lifetime_value_attribute_name;

        return $this;
    }

    /**
     * Gets data_connection_type
     *
     * @return string|null
     */
    public function getDataConnectionType()
    {
        return $this->container['data_connection_type'];
    }

    /**
     * Sets data_connection_type
     *
     * @param string|null $data_connection_type data_connection_type
     *
     * @return $this
     */
    public function setDataConnectionType($data_connection_type)
    {
        $this->container['data_connection_type'] = $data_connection_type;

        return $this;
    }

    /**
     * Gets event_num
     *
     * @return int|null
     */
    public function getEventNum()
    {
        return $this->container['event_num'];
    }

    /**
     * Sets event_num
     *
     * @param int|null $event_num event_num
     *
     * @return $this
     */
    public function setEventNum($event_num)
    {
        $this->container['event_num'] = $event_num;

        return $this;
    }

    /**
     * Gets view_controller
     *
     * @return string|null
     */
    public function getViewController()
    {
        return $this->container['view_controller'];
    }

    /**
     * Sets view_controller
     *
     * @param string|null $view_controller view_controller
     *
     * @return $this
     */
    public function setViewController($view_controller)
    {
        $this->container['view_controller'] = $view_controller;

        return $this;
    }

    /**
     * Gets is_main_thread
     *
     * @return bool|null
     */
    public function getIsMainThread()
    {
        return $this->container['is_main_thread'];
    }

    /**
     * Sets is_main_thread
     *
     * @param bool|null $is_main_thread is_main_thread
     *
     * @return $this
     */
    public function setIsMainThread($is_main_thread)
    {
        $this->container['is_main_thread'] = $is_main_thread;

        return $this;
    }

    /**
     * Gets canonical_name
     *
     * @return string|null
     */
    public function getCanonicalName()
    {
        return $this->container['canonical_name'];
    }

    /**
     * Sets canonical_name
     *
     * @param string|null $canonical_name canonical_name
     *
     * @return $this
     */
    public function setCanonicalName($canonical_name)
    {
        $this->container['canonical_name'] = $canonical_name;

        return $this;
    }

    /**
     * Gets event_system_notification_info
     *
     * @return \OpenAPI\Client\Model\EventSystemNotificationInfo|null
     */
    public function getEventSystemNotificationInfo()
    {
        return $this->container['event_system_notification_info'];
    }

    /**
     * Sets event_system_notification_info
     *
     * @param \OpenAPI\Client\Model\EventSystemNotificationInfo|null $event_system_notification_info event_system_notification_info
     *
     * @return $this
     */
    public function setEventSystemNotificationInfo($event_system_notification_info)
    {
        $this->container['event_system_notification_info'] = $event_system_notification_info;

        return $this;
    }

    /**
     * Gets custom_event_type
     *
     * @return string
     */
    public function getCustomEventType()
    {
        return $this->container['custom_event_type'];
    }

    /**
     * Sets custom_event_type
     *
     * @param string $custom_event_type custom_event_type
     *
     * @return $this
     */
    public function setCustomEventType($custom_event_type)
    {
        $allowedValues = $this->getCustomEventTypeAllowableValues();
        if (!in_array($custom_event_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'custom_event_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['custom_event_type'] = $custom_event_type;

        return $this;
    }

    /**
     * Gets event_name
     *
     * @return string
     */
    public function getEventName()
    {
        return $this->container['event_name'];
    }

    /**
     * Sets event_name
     *
     * @param string $event_name event_name
     *
     * @return $this
     */
    public function setEventName($event_name)
    {
        $this->container['event_name'] = $event_name;

        return $this;
    }

    /**
     * Gets custom_flags
     *
     * @return map[string,string]|null
     */
    public function getCustomFlags()
    {
        return $this->container['custom_flags'];
    }

    /**
     * Sets custom_flags
     *
     * @param map[string,string]|null $custom_flags custom_flags
     *
     * @return $this
     */
    public function setCustomFlags($custom_flags)
    {
        $this->container['custom_flags'] = $custom_flags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


