<?php
/**
 * CustomEventDataAllOf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomEventDataAllOf Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomEventDataAllOf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomEventData_allOf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'custom_event_type' => 'string',
        'event_name' => 'string',
        'custom_flags' => 'map[string,string]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'custom_event_type' => null,
        'event_name' => null,
        'custom_flags' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'custom_event_type' => 'custom_event_type',
        'event_name' => 'event_name',
        'custom_flags' => 'custom_flags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'custom_event_type' => 'setCustomEventType',
        'event_name' => 'setEventName',
        'custom_flags' => 'setCustomFlags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'custom_event_type' => 'getCustomEventType',
        'event_name' => 'getEventName',
        'custom_flags' => 'getCustomFlags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const CUSTOM_EVENT_TYPE_NAVIGATION = 'navigation';
    const CUSTOM_EVENT_TYPE_LOCATION = 'location';
    const CUSTOM_EVENT_TYPE_SEARCH = 'search';
    const CUSTOM_EVENT_TYPE_TRANSACTION = 'transaction';
    const CUSTOM_EVENT_TYPE_USER_CONTENT = 'user_content';
    const CUSTOM_EVENT_TYPE_USER_PREFERENCE = 'user_preference';
    const CUSTOM_EVENT_TYPE_SOCIAL = 'social';
    const CUSTOM_EVENT_TYPE_OTHER = 'other';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCustomEventTypeAllowableValues()
    {
        return [
            self::CUSTOM_EVENT_TYPE_NAVIGATION,
            self::CUSTOM_EVENT_TYPE_LOCATION,
            self::CUSTOM_EVENT_TYPE_SEARCH,
            self::CUSTOM_EVENT_TYPE_TRANSACTION,
            self::CUSTOM_EVENT_TYPE_USER_CONTENT,
            self::CUSTOM_EVENT_TYPE_USER_PREFERENCE,
            self::CUSTOM_EVENT_TYPE_SOCIAL,
            self::CUSTOM_EVENT_TYPE_OTHER,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['custom_event_type'] = isset($data['custom_event_type']) ? $data['custom_event_type'] : 'other';
        $this->container['event_name'] = isset($data['event_name']) ? $data['event_name'] : null;
        $this->container['custom_flags'] = isset($data['custom_flags']) ? $data['custom_flags'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['custom_event_type'] === null) {
            $invalidProperties[] = "'custom_event_type' can't be null";
        }
        $allowedValues = $this->getCustomEventTypeAllowableValues();
        if (!is_null($this->container['custom_event_type']) && !in_array($this->container['custom_event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'custom_event_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['event_name'] === null) {
            $invalidProperties[] = "'event_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets custom_event_type
     *
     * @return string
     */
    public function getCustomEventType()
    {
        return $this->container['custom_event_type'];
    }

    /**
     * Sets custom_event_type
     *
     * @param string $custom_event_type custom_event_type
     *
     * @return $this
     */
    public function setCustomEventType($custom_event_type)
    {
        $allowedValues = $this->getCustomEventTypeAllowableValues();
        if (!in_array($custom_event_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'custom_event_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['custom_event_type'] = $custom_event_type;

        return $this;
    }

    /**
     * Gets event_name
     *
     * @return string
     */
    public function getEventName()
    {
        return $this->container['event_name'];
    }

    /**
     * Sets event_name
     *
     * @param string $event_name event_name
     *
     * @return $this
     */
    public function setEventName($event_name)
    {
        $this->container['event_name'] = $event_name;

        return $this;
    }

    /**
     * Gets custom_flags
     *
     * @return map[string,string]|null
     */
    public function getCustomFlags()
    {
        return $this->container['custom_flags'];
    }

    /**
     * Sets custom_flags
     *
     * @param map[string,string]|null $custom_flags custom_flags
     *
     * @return $this
     */
    public function setCustomFlags($custom_flags)
    {
        $this->container['custom_flags'] = $custom_flags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


