<?php
/**
 * DeviceCurrentState
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DeviceCurrentState Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeviceCurrentState implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeviceCurrentState';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'time_since_start_ms' => 'int',
        'battery_level' => 'float',
        'data_connection_type' => 'string',
        'data_connection_type_detail' => 'string',
        'gps_state' => 'bool',
        'total_system_memory_usage_bytes' => 'int',
        'disk_space_free_bytes' => 'int',
        'external_disk_space_free_bytes' => 'int',
        'cpu' => 'string',
        'system_memory_available_bytes' => 'float',
        'system_memory_low' => 'bool',
        'system_memory_threshold_bytes' => 'float',
        'application_memory_available_bytes' => 'float',
        'application_memory_max_bytes' => 'float',
        'application_memory_total_bytes' => 'float',
        'device_orientation' => 'string',
        'status_bar_orientation' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'time_since_start_ms' => null,
        'battery_level' => null,
        'data_connection_type' => null,
        'data_connection_type_detail' => null,
        'gps_state' => null,
        'total_system_memory_usage_bytes' => null,
        'disk_space_free_bytes' => null,
        'external_disk_space_free_bytes' => null,
        'cpu' => null,
        'system_memory_available_bytes' => null,
        'system_memory_low' => null,
        'system_memory_threshold_bytes' => null,
        'application_memory_available_bytes' => null,
        'application_memory_max_bytes' => null,
        'application_memory_total_bytes' => null,
        'device_orientation' => null,
        'status_bar_orientation' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'time_since_start_ms' => 'time_since_start_ms',
        'battery_level' => 'battery_level',
        'data_connection_type' => 'data_connection_type',
        'data_connection_type_detail' => 'data_connection_type_detail',
        'gps_state' => 'gps_state',
        'total_system_memory_usage_bytes' => 'total_system_memory_usage_bytes',
        'disk_space_free_bytes' => 'disk_space_free_bytes',
        'external_disk_space_free_bytes' => 'external_disk_space_free_bytes',
        'cpu' => 'cpu',
        'system_memory_available_bytes' => 'system_memory_available_bytes',
        'system_memory_low' => 'system_memory_low',
        'system_memory_threshold_bytes' => 'system_memory_threshold_bytes',
        'application_memory_available_bytes' => 'application_memory_available_bytes',
        'application_memory_max_bytes' => 'application_memory_max_bytes',
        'application_memory_total_bytes' => 'application_memory_total_bytes',
        'device_orientation' => 'device_orientation',
        'status_bar_orientation' => 'status_bar_orientation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'time_since_start_ms' => 'setTimeSinceStartMs',
        'battery_level' => 'setBatteryLevel',
        'data_connection_type' => 'setDataConnectionType',
        'data_connection_type_detail' => 'setDataConnectionTypeDetail',
        'gps_state' => 'setGpsState',
        'total_system_memory_usage_bytes' => 'setTotalSystemMemoryUsageBytes',
        'disk_space_free_bytes' => 'setDiskSpaceFreeBytes',
        'external_disk_space_free_bytes' => 'setExternalDiskSpaceFreeBytes',
        'cpu' => 'setCpu',
        'system_memory_available_bytes' => 'setSystemMemoryAvailableBytes',
        'system_memory_low' => 'setSystemMemoryLow',
        'system_memory_threshold_bytes' => 'setSystemMemoryThresholdBytes',
        'application_memory_available_bytes' => 'setApplicationMemoryAvailableBytes',
        'application_memory_max_bytes' => 'setApplicationMemoryMaxBytes',
        'application_memory_total_bytes' => 'setApplicationMemoryTotalBytes',
        'device_orientation' => 'setDeviceOrientation',
        'status_bar_orientation' => 'setStatusBarOrientation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'time_since_start_ms' => 'getTimeSinceStartMs',
        'battery_level' => 'getBatteryLevel',
        'data_connection_type' => 'getDataConnectionType',
        'data_connection_type_detail' => 'getDataConnectionTypeDetail',
        'gps_state' => 'getGpsState',
        'total_system_memory_usage_bytes' => 'getTotalSystemMemoryUsageBytes',
        'disk_space_free_bytes' => 'getDiskSpaceFreeBytes',
        'external_disk_space_free_bytes' => 'getExternalDiskSpaceFreeBytes',
        'cpu' => 'getCpu',
        'system_memory_available_bytes' => 'getSystemMemoryAvailableBytes',
        'system_memory_low' => 'getSystemMemoryLow',
        'system_memory_threshold_bytes' => 'getSystemMemoryThresholdBytes',
        'application_memory_available_bytes' => 'getApplicationMemoryAvailableBytes',
        'application_memory_max_bytes' => 'getApplicationMemoryMaxBytes',
        'application_memory_total_bytes' => 'getApplicationMemoryTotalBytes',
        'device_orientation' => 'getDeviceOrientation',
        'status_bar_orientation' => 'getStatusBarOrientation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const DEVICE_ORIENTATION_PORTRAIT = 'portrait';
    const DEVICE_ORIENTATION_PORTRAIT_UPSIDE_DOWN = 'portrait_upside_down';
    const DEVICE_ORIENTATION_LANDSCAPE = 'landscape';
    const DEVICE_ORIENTATION_LANDSCAPE_LEFT = 'LandscapeLeft';
    const DEVICE_ORIENTATION_LANDSCAPE_RIGHT = 'LandscapeRight';
    const DEVICE_ORIENTATION_FACE_UP = 'FaceUp';
    const DEVICE_ORIENTATION_FACE_DOWN = 'FaceDown';
    const DEVICE_ORIENTATION_SQUARE = 'Square';
    const STATUS_BAR_ORIENTATION_PORTRAIT = 'portrait';
    const STATUS_BAR_ORIENTATION_PORTRAIT_UPSIDE_DOWN = 'portrait_upside_down';
    const STATUS_BAR_ORIENTATION_LANDSCAPE = 'landscape';
    const STATUS_BAR_ORIENTATION_LANDSCAPE_LEFT = 'LandscapeLeft';
    const STATUS_BAR_ORIENTATION_LANDSCAPE_RIGHT = 'LandscapeRight';
    const STATUS_BAR_ORIENTATION_FACE_UP = 'FaceUp';
    const STATUS_BAR_ORIENTATION_FACE_DOWN = 'FaceDown';
    const STATUS_BAR_ORIENTATION_SQUARE = 'Square';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeviceOrientationAllowableValues()
    {
        return [
            self::DEVICE_ORIENTATION_PORTRAIT,
            self::DEVICE_ORIENTATION_PORTRAIT_UPSIDE_DOWN,
            self::DEVICE_ORIENTATION_LANDSCAPE,
            self::DEVICE_ORIENTATION_LANDSCAPE_LEFT,
            self::DEVICE_ORIENTATION_LANDSCAPE_RIGHT,
            self::DEVICE_ORIENTATION_FACE_UP,
            self::DEVICE_ORIENTATION_FACE_DOWN,
            self::DEVICE_ORIENTATION_SQUARE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusBarOrientationAllowableValues()
    {
        return [
            self::STATUS_BAR_ORIENTATION_PORTRAIT,
            self::STATUS_BAR_ORIENTATION_PORTRAIT_UPSIDE_DOWN,
            self::STATUS_BAR_ORIENTATION_LANDSCAPE,
            self::STATUS_BAR_ORIENTATION_LANDSCAPE_LEFT,
            self::STATUS_BAR_ORIENTATION_LANDSCAPE_RIGHT,
            self::STATUS_BAR_ORIENTATION_FACE_UP,
            self::STATUS_BAR_ORIENTATION_FACE_DOWN,
            self::STATUS_BAR_ORIENTATION_SQUARE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['time_since_start_ms'] = isset($data['time_since_start_ms']) ? $data['time_since_start_ms'] : null;
        $this->container['battery_level'] = isset($data['battery_level']) ? $data['battery_level'] : null;
        $this->container['data_connection_type'] = isset($data['data_connection_type']) ? $data['data_connection_type'] : null;
        $this->container['data_connection_type_detail'] = isset($data['data_connection_type_detail']) ? $data['data_connection_type_detail'] : null;
        $this->container['gps_state'] = isset($data['gps_state']) ? $data['gps_state'] : null;
        $this->container['total_system_memory_usage_bytes'] = isset($data['total_system_memory_usage_bytes']) ? $data['total_system_memory_usage_bytes'] : null;
        $this->container['disk_space_free_bytes'] = isset($data['disk_space_free_bytes']) ? $data['disk_space_free_bytes'] : null;
        $this->container['external_disk_space_free_bytes'] = isset($data['external_disk_space_free_bytes']) ? $data['external_disk_space_free_bytes'] : null;
        $this->container['cpu'] = isset($data['cpu']) ? $data['cpu'] : null;
        $this->container['system_memory_available_bytes'] = isset($data['system_memory_available_bytes']) ? $data['system_memory_available_bytes'] : null;
        $this->container['system_memory_low'] = isset($data['system_memory_low']) ? $data['system_memory_low'] : null;
        $this->container['system_memory_threshold_bytes'] = isset($data['system_memory_threshold_bytes']) ? $data['system_memory_threshold_bytes'] : null;
        $this->container['application_memory_available_bytes'] = isset($data['application_memory_available_bytes']) ? $data['application_memory_available_bytes'] : null;
        $this->container['application_memory_max_bytes'] = isset($data['application_memory_max_bytes']) ? $data['application_memory_max_bytes'] : null;
        $this->container['application_memory_total_bytes'] = isset($data['application_memory_total_bytes']) ? $data['application_memory_total_bytes'] : null;
        $this->container['device_orientation'] = isset($data['device_orientation']) ? $data['device_orientation'] : null;
        $this->container['status_bar_orientation'] = isset($data['status_bar_orientation']) ? $data['status_bar_orientation'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDeviceOrientationAllowableValues();
        if (!is_null($this->container['device_orientation']) && !in_array($this->container['device_orientation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'device_orientation', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusBarOrientationAllowableValues();
        if (!is_null($this->container['status_bar_orientation']) && !in_array($this->container['status_bar_orientation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status_bar_orientation', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets time_since_start_ms
     *
     * @return int|null
     */
    public function getTimeSinceStartMs()
    {
        return $this->container['time_since_start_ms'];
    }

    /**
     * Sets time_since_start_ms
     *
     * @param int|null $time_since_start_ms time_since_start_ms
     *
     * @return $this
     */
    public function setTimeSinceStartMs($time_since_start_ms)
    {
        $this->container['time_since_start_ms'] = $time_since_start_ms;

        return $this;
    }

    /**
     * Gets battery_level
     *
     * @return float|null
     */
    public function getBatteryLevel()
    {
        return $this->container['battery_level'];
    }

    /**
     * Sets battery_level
     *
     * @param float|null $battery_level battery_level
     *
     * @return $this
     */
    public function setBatteryLevel($battery_level)
    {
        $this->container['battery_level'] = $battery_level;

        return $this;
    }

    /**
     * Gets data_connection_type
     *
     * @return string|null
     */
    public function getDataConnectionType()
    {
        return $this->container['data_connection_type'];
    }

    /**
     * Sets data_connection_type
     *
     * @param string|null $data_connection_type data_connection_type
     *
     * @return $this
     */
    public function setDataConnectionType($data_connection_type)
    {
        $this->container['data_connection_type'] = $data_connection_type;

        return $this;
    }

    /**
     * Gets data_connection_type_detail
     *
     * @return string|null
     */
    public function getDataConnectionTypeDetail()
    {
        return $this->container['data_connection_type_detail'];
    }

    /**
     * Sets data_connection_type_detail
     *
     * @param string|null $data_connection_type_detail data_connection_type_detail
     *
     * @return $this
     */
    public function setDataConnectionTypeDetail($data_connection_type_detail)
    {
        $this->container['data_connection_type_detail'] = $data_connection_type_detail;

        return $this;
    }

    /**
     * Gets gps_state
     *
     * @return bool|null
     */
    public function getGpsState()
    {
        return $this->container['gps_state'];
    }

    /**
     * Sets gps_state
     *
     * @param bool|null $gps_state gps_state
     *
     * @return $this
     */
    public function setGpsState($gps_state)
    {
        $this->container['gps_state'] = $gps_state;

        return $this;
    }

    /**
     * Gets total_system_memory_usage_bytes
     *
     * @return int|null
     */
    public function getTotalSystemMemoryUsageBytes()
    {
        return $this->container['total_system_memory_usage_bytes'];
    }

    /**
     * Sets total_system_memory_usage_bytes
     *
     * @param int|null $total_system_memory_usage_bytes total_system_memory_usage_bytes
     *
     * @return $this
     */
    public function setTotalSystemMemoryUsageBytes($total_system_memory_usage_bytes)
    {
        $this->container['total_system_memory_usage_bytes'] = $total_system_memory_usage_bytes;

        return $this;
    }

    /**
     * Gets disk_space_free_bytes
     *
     * @return int|null
     */
    public function getDiskSpaceFreeBytes()
    {
        return $this->container['disk_space_free_bytes'];
    }

    /**
     * Sets disk_space_free_bytes
     *
     * @param int|null $disk_space_free_bytes disk_space_free_bytes
     *
     * @return $this
     */
    public function setDiskSpaceFreeBytes($disk_space_free_bytes)
    {
        $this->container['disk_space_free_bytes'] = $disk_space_free_bytes;

        return $this;
    }

    /**
     * Gets external_disk_space_free_bytes
     *
     * @return int|null
     */
    public function getExternalDiskSpaceFreeBytes()
    {
        return $this->container['external_disk_space_free_bytes'];
    }

    /**
     * Sets external_disk_space_free_bytes
     *
     * @param int|null $external_disk_space_free_bytes external_disk_space_free_bytes
     *
     * @return $this
     */
    public function setExternalDiskSpaceFreeBytes($external_disk_space_free_bytes)
    {
        $this->container['external_disk_space_free_bytes'] = $external_disk_space_free_bytes;

        return $this;
    }

    /**
     * Gets cpu
     *
     * @return string|null
     */
    public function getCpu()
    {
        return $this->container['cpu'];
    }

    /**
     * Sets cpu
     *
     * @param string|null $cpu cpu
     *
     * @return $this
     */
    public function setCpu($cpu)
    {
        $this->container['cpu'] = $cpu;

        return $this;
    }

    /**
     * Gets system_memory_available_bytes
     *
     * @return float|null
     */
    public function getSystemMemoryAvailableBytes()
    {
        return $this->container['system_memory_available_bytes'];
    }

    /**
     * Sets system_memory_available_bytes
     *
     * @param float|null $system_memory_available_bytes system_memory_available_bytes
     *
     * @return $this
     */
    public function setSystemMemoryAvailableBytes($system_memory_available_bytes)
    {
        $this->container['system_memory_available_bytes'] = $system_memory_available_bytes;

        return $this;
    }

    /**
     * Gets system_memory_low
     *
     * @return bool|null
     */
    public function getSystemMemoryLow()
    {
        return $this->container['system_memory_low'];
    }

    /**
     * Sets system_memory_low
     *
     * @param bool|null $system_memory_low system_memory_low
     *
     * @return $this
     */
    public function setSystemMemoryLow($system_memory_low)
    {
        $this->container['system_memory_low'] = $system_memory_low;

        return $this;
    }

    /**
     * Gets system_memory_threshold_bytes
     *
     * @return float|null
     */
    public function getSystemMemoryThresholdBytes()
    {
        return $this->container['system_memory_threshold_bytes'];
    }

    /**
     * Sets system_memory_threshold_bytes
     *
     * @param float|null $system_memory_threshold_bytes system_memory_threshold_bytes
     *
     * @return $this
     */
    public function setSystemMemoryThresholdBytes($system_memory_threshold_bytes)
    {
        $this->container['system_memory_threshold_bytes'] = $system_memory_threshold_bytes;

        return $this;
    }

    /**
     * Gets application_memory_available_bytes
     *
     * @return float|null
     */
    public function getApplicationMemoryAvailableBytes()
    {
        return $this->container['application_memory_available_bytes'];
    }

    /**
     * Sets application_memory_available_bytes
     *
     * @param float|null $application_memory_available_bytes application_memory_available_bytes
     *
     * @return $this
     */
    public function setApplicationMemoryAvailableBytes($application_memory_available_bytes)
    {
        $this->container['application_memory_available_bytes'] = $application_memory_available_bytes;

        return $this;
    }

    /**
     * Gets application_memory_max_bytes
     *
     * @return float|null
     */
    public function getApplicationMemoryMaxBytes()
    {
        return $this->container['application_memory_max_bytes'];
    }

    /**
     * Sets application_memory_max_bytes
     *
     * @param float|null $application_memory_max_bytes application_memory_max_bytes
     *
     * @return $this
     */
    public function setApplicationMemoryMaxBytes($application_memory_max_bytes)
    {
        $this->container['application_memory_max_bytes'] = $application_memory_max_bytes;

        return $this;
    }

    /**
     * Gets application_memory_total_bytes
     *
     * @return float|null
     */
    public function getApplicationMemoryTotalBytes()
    {
        return $this->container['application_memory_total_bytes'];
    }

    /**
     * Sets application_memory_total_bytes
     *
     * @param float|null $application_memory_total_bytes application_memory_total_bytes
     *
     * @return $this
     */
    public function setApplicationMemoryTotalBytes($application_memory_total_bytes)
    {
        $this->container['application_memory_total_bytes'] = $application_memory_total_bytes;

        return $this;
    }

    /**
     * Gets device_orientation
     *
     * @return string|null
     */
    public function getDeviceOrientation()
    {
        return $this->container['device_orientation'];
    }

    /**
     * Sets device_orientation
     *
     * @param string|null $device_orientation device_orientation
     *
     * @return $this
     */
    public function setDeviceOrientation($device_orientation)
    {
        $allowedValues = $this->getDeviceOrientationAllowableValues();
        if (!is_null($device_orientation) && !in_array($device_orientation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'device_orientation', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['device_orientation'] = $device_orientation;

        return $this;
    }

    /**
     * Gets status_bar_orientation
     *
     * @return string|null
     */
    public function getStatusBarOrientation()
    {
        return $this->container['status_bar_orientation'];
    }

    /**
     * Sets status_bar_orientation
     *
     * @param string|null $status_bar_orientation status_bar_orientation
     *
     * @return $this
     */
    public function setStatusBarOrientation($status_bar_orientation)
    {
        $allowedValues = $this->getStatusBarOrientationAllowableValues();
        if (!is_null($status_bar_orientation) && !in_array($status_bar_orientation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status_bar_orientation', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status_bar_orientation'] = $status_bar_orientation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


