<?php
/**
 * DeviceInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DeviceInformation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeviceInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeviceInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'brand' => 'string',
        'product' => 'string',
        'device' => 'string',
        'android_uuid' => 'string',
        'device_manufacturer' => 'string',
        'platform' => 'string',
        'os_version' => 'string',
        'device_model' => 'string',
        'screen_height' => 'int',
        'screen_width' => 'int',
        'screen_dpi' => 'int',
        'device_country' => 'string',
        'locale_language' => 'string',
        'locale_country' => 'string',
        'network_country' => 'string',
        'network_carrier' => 'string',
        'network_code' => 'string',
        'network_mobile_country_code' => 'string',
        'timezone_offset' => 'int',
        'build_identifier' => 'string',
        'http_header_user_agent' => 'string',
        'ios_advertising_id' => 'string',
        'push_token' => 'string',
        'cpu_architecture' => 'string',
        'is_tablet' => 'bool',
        'push_notification_sound_enabled' => 'bool',
        'push_notification_vibrate_enabled' => 'bool',
        'radio_access_technology' => 'string',
        'supports_telephony' => 'bool',
        'has_nfc' => 'bool',
        'bluetooth_enabled' => 'bool',
        'bluetooth_version' => 'string',
        'ios_idfv' => 'string',
        'android_advertising_id' => 'string',
        'build_version_release' => 'string',
        'limit_ad_tracking' => 'bool',
        'amp_id' => 'string',
        'is_dst' => 'bool',
        'roku_advertising_id' => 'string',
        'roku_publisher_id' => 'string',
        'microsoft_advertising_id' => 'string',
        'microsoft_publisher_id' => 'string',
        'fire_advertising_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'brand' => null,
        'product' => null,
        'device' => null,
        'android_uuid' => null,
        'device_manufacturer' => null,
        'platform' => null,
        'os_version' => null,
        'device_model' => null,
        'screen_height' => null,
        'screen_width' => null,
        'screen_dpi' => null,
        'device_country' => null,
        'locale_language' => null,
        'locale_country' => null,
        'network_country' => null,
        'network_carrier' => null,
        'network_code' => null,
        'network_mobile_country_code' => null,
        'timezone_offset' => null,
        'build_identifier' => null,
        'http_header_user_agent' => null,
        'ios_advertising_id' => null,
        'push_token' => null,
        'cpu_architecture' => null,
        'is_tablet' => null,
        'push_notification_sound_enabled' => null,
        'push_notification_vibrate_enabled' => null,
        'radio_access_technology' => null,
        'supports_telephony' => null,
        'has_nfc' => null,
        'bluetooth_enabled' => null,
        'bluetooth_version' => null,
        'ios_idfv' => null,
        'android_advertising_id' => null,
        'build_version_release' => null,
        'limit_ad_tracking' => null,
        'amp_id' => null,
        'is_dst' => null,
        'roku_advertising_id' => null,
        'roku_publisher_id' => null,
        'microsoft_advertising_id' => null,
        'microsoft_publisher_id' => null,
        'fire_advertising_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'brand' => 'brand',
        'product' => 'product',
        'device' => 'device',
        'android_uuid' => 'android_uuid',
        'device_manufacturer' => 'device_manufacturer',
        'platform' => 'platform',
        'os_version' => 'os_version',
        'device_model' => 'device_model',
        'screen_height' => 'screen_height',
        'screen_width' => 'screen_width',
        'screen_dpi' => 'screen_dpi',
        'device_country' => 'device_country',
        'locale_language' => 'locale_language',
        'locale_country' => 'locale_country',
        'network_country' => 'network_country',
        'network_carrier' => 'network_carrier',
        'network_code' => 'network_code',
        'network_mobile_country_code' => 'network_mobile_country_code',
        'timezone_offset' => 'timezone_offset',
        'build_identifier' => 'build_identifier',
        'http_header_user_agent' => 'http_header_user_agent',
        'ios_advertising_id' => 'ios_advertising_id',
        'push_token' => 'push_token',
        'cpu_architecture' => 'cpu_architecture',
        'is_tablet' => 'is_tablet',
        'push_notification_sound_enabled' => 'push_notification_sound_enabled',
        'push_notification_vibrate_enabled' => 'push_notification_vibrate_enabled',
        'radio_access_technology' => 'radio_access_technology',
        'supports_telephony' => 'supports_telephony',
        'has_nfc' => 'has_nfc',
        'bluetooth_enabled' => 'bluetooth_enabled',
        'bluetooth_version' => 'bluetooth_version',
        'ios_idfv' => 'ios_idfv',
        'android_advertising_id' => 'android_advertising_id',
        'build_version_release' => 'build_version_release',
        'limit_ad_tracking' => 'limit_ad_tracking',
        'amp_id' => 'amp_id',
        'is_dst' => 'is_dst',
        'roku_advertising_id' => 'roku_advertising_id',
        'roku_publisher_id' => 'roku_publisher_id',
        'microsoft_advertising_id' => 'microsoft_advertising_id',
        'microsoft_publisher_id' => 'microsoft_publisher_id',
        'fire_advertising_id' => 'fire_advertising_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'brand' => 'setBrand',
        'product' => 'setProduct',
        'device' => 'setDevice',
        'android_uuid' => 'setAndroidUuid',
        'device_manufacturer' => 'setDeviceManufacturer',
        'platform' => 'setPlatform',
        'os_version' => 'setOsVersion',
        'device_model' => 'setDeviceModel',
        'screen_height' => 'setScreenHeight',
        'screen_width' => 'setScreenWidth',
        'screen_dpi' => 'setScreenDpi',
        'device_country' => 'setDeviceCountry',
        'locale_language' => 'setLocaleLanguage',
        'locale_country' => 'setLocaleCountry',
        'network_country' => 'setNetworkCountry',
        'network_carrier' => 'setNetworkCarrier',
        'network_code' => 'setNetworkCode',
        'network_mobile_country_code' => 'setNetworkMobileCountryCode',
        'timezone_offset' => 'setTimezoneOffset',
        'build_identifier' => 'setBuildIdentifier',
        'http_header_user_agent' => 'setHttpHeaderUserAgent',
        'ios_advertising_id' => 'setIosAdvertisingId',
        'push_token' => 'setPushToken',
        'cpu_architecture' => 'setCpuArchitecture',
        'is_tablet' => 'setIsTablet',
        'push_notification_sound_enabled' => 'setPushNotificationSoundEnabled',
        'push_notification_vibrate_enabled' => 'setPushNotificationVibrateEnabled',
        'radio_access_technology' => 'setRadioAccessTechnology',
        'supports_telephony' => 'setSupportsTelephony',
        'has_nfc' => 'setHasNfc',
        'bluetooth_enabled' => 'setBluetoothEnabled',
        'bluetooth_version' => 'setBluetoothVersion',
        'ios_idfv' => 'setIosIdfv',
        'android_advertising_id' => 'setAndroidAdvertisingId',
        'build_version_release' => 'setBuildVersionRelease',
        'limit_ad_tracking' => 'setLimitAdTracking',
        'amp_id' => 'setAmpId',
        'is_dst' => 'setIsDst',
        'roku_advertising_id' => 'setRokuAdvertisingId',
        'roku_publisher_id' => 'setRokuPublisherId',
        'microsoft_advertising_id' => 'setMicrosoftAdvertisingId',
        'microsoft_publisher_id' => 'setMicrosoftPublisherId',
        'fire_advertising_id' => 'setFireAdvertisingId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'brand' => 'getBrand',
        'product' => 'getProduct',
        'device' => 'getDevice',
        'android_uuid' => 'getAndroidUuid',
        'device_manufacturer' => 'getDeviceManufacturer',
        'platform' => 'getPlatform',
        'os_version' => 'getOsVersion',
        'device_model' => 'getDeviceModel',
        'screen_height' => 'getScreenHeight',
        'screen_width' => 'getScreenWidth',
        'screen_dpi' => 'getScreenDpi',
        'device_country' => 'getDeviceCountry',
        'locale_language' => 'getLocaleLanguage',
        'locale_country' => 'getLocaleCountry',
        'network_country' => 'getNetworkCountry',
        'network_carrier' => 'getNetworkCarrier',
        'network_code' => 'getNetworkCode',
        'network_mobile_country_code' => 'getNetworkMobileCountryCode',
        'timezone_offset' => 'getTimezoneOffset',
        'build_identifier' => 'getBuildIdentifier',
        'http_header_user_agent' => 'getHttpHeaderUserAgent',
        'ios_advertising_id' => 'getIosAdvertisingId',
        'push_token' => 'getPushToken',
        'cpu_architecture' => 'getCpuArchitecture',
        'is_tablet' => 'getIsTablet',
        'push_notification_sound_enabled' => 'getPushNotificationSoundEnabled',
        'push_notification_vibrate_enabled' => 'getPushNotificationVibrateEnabled',
        'radio_access_technology' => 'getRadioAccessTechnology',
        'supports_telephony' => 'getSupportsTelephony',
        'has_nfc' => 'getHasNfc',
        'bluetooth_enabled' => 'getBluetoothEnabled',
        'bluetooth_version' => 'getBluetoothVersion',
        'ios_idfv' => 'getIosIdfv',
        'android_advertising_id' => 'getAndroidAdvertisingId',
        'build_version_release' => 'getBuildVersionRelease',
        'limit_ad_tracking' => 'getLimitAdTracking',
        'amp_id' => 'getAmpId',
        'is_dst' => 'getIsDst',
        'roku_advertising_id' => 'getRokuAdvertisingId',
        'roku_publisher_id' => 'getRokuPublisherId',
        'microsoft_advertising_id' => 'getMicrosoftAdvertisingId',
        'microsoft_publisher_id' => 'getMicrosoftPublisherId',
        'fire_advertising_id' => 'getFireAdvertisingId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const PLATFORM_I_OS = 'iOS';
    const PLATFORM_ANDROID = 'Android';
    const PLATFORM_WEB = 'web';
    const PLATFORM_DESKTOP = 'desktop';
    const PLATFORM_TV_OS = 'tvOS';
    const PLATFORM_ROKU = 'roku';
    const PLATFORM_OUT_OF_BAND = 'out_of_band';
    const PLATFORM_SMART_TV = 'smart_tv';
    const PLATFORM_XBOX = 'xbox';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPlatformAllowableValues()
    {
        return [
            self::PLATFORM_I_OS,
            self::PLATFORM_ANDROID,
            self::PLATFORM_WEB,
            self::PLATFORM_DESKTOP,
            self::PLATFORM_TV_OS,
            self::PLATFORM_ROKU,
            self::PLATFORM_OUT_OF_BAND,
            self::PLATFORM_SMART_TV,
            self::PLATFORM_XBOX,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['brand'] = isset($data['brand']) ? $data['brand'] : null;
        $this->container['product'] = isset($data['product']) ? $data['product'] : null;
        $this->container['device'] = isset($data['device']) ? $data['device'] : null;
        $this->container['android_uuid'] = isset($data['android_uuid']) ? $data['android_uuid'] : null;
        $this->container['device_manufacturer'] = isset($data['device_manufacturer']) ? $data['device_manufacturer'] : null;
        $this->container['platform'] = isset($data['platform']) ? $data['platform'] : null;
        $this->container['os_version'] = isset($data['os_version']) ? $data['os_version'] : null;
        $this->container['device_model'] = isset($data['device_model']) ? $data['device_model'] : null;
        $this->container['screen_height'] = isset($data['screen_height']) ? $data['screen_height'] : null;
        $this->container['screen_width'] = isset($data['screen_width']) ? $data['screen_width'] : null;
        $this->container['screen_dpi'] = isset($data['screen_dpi']) ? $data['screen_dpi'] : null;
        $this->container['device_country'] = isset($data['device_country']) ? $data['device_country'] : null;
        $this->container['locale_language'] = isset($data['locale_language']) ? $data['locale_language'] : null;
        $this->container['locale_country'] = isset($data['locale_country']) ? $data['locale_country'] : null;
        $this->container['network_country'] = isset($data['network_country']) ? $data['network_country'] : null;
        $this->container['network_carrier'] = isset($data['network_carrier']) ? $data['network_carrier'] : null;
        $this->container['network_code'] = isset($data['network_code']) ? $data['network_code'] : null;
        $this->container['network_mobile_country_code'] = isset($data['network_mobile_country_code']) ? $data['network_mobile_country_code'] : null;
        $this->container['timezone_offset'] = isset($data['timezone_offset']) ? $data['timezone_offset'] : null;
        $this->container['build_identifier'] = isset($data['build_identifier']) ? $data['build_identifier'] : null;
        $this->container['http_header_user_agent'] = isset($data['http_header_user_agent']) ? $data['http_header_user_agent'] : null;
        $this->container['ios_advertising_id'] = isset($data['ios_advertising_id']) ? $data['ios_advertising_id'] : null;
        $this->container['push_token'] = isset($data['push_token']) ? $data['push_token'] : null;
        $this->container['cpu_architecture'] = isset($data['cpu_architecture']) ? $data['cpu_architecture'] : null;
        $this->container['is_tablet'] = isset($data['is_tablet']) ? $data['is_tablet'] : null;
        $this->container['push_notification_sound_enabled'] = isset($data['push_notification_sound_enabled']) ? $data['push_notification_sound_enabled'] : null;
        $this->container['push_notification_vibrate_enabled'] = isset($data['push_notification_vibrate_enabled']) ? $data['push_notification_vibrate_enabled'] : null;
        $this->container['radio_access_technology'] = isset($data['radio_access_technology']) ? $data['radio_access_technology'] : null;
        $this->container['supports_telephony'] = isset($data['supports_telephony']) ? $data['supports_telephony'] : null;
        $this->container['has_nfc'] = isset($data['has_nfc']) ? $data['has_nfc'] : null;
        $this->container['bluetooth_enabled'] = isset($data['bluetooth_enabled']) ? $data['bluetooth_enabled'] : null;
        $this->container['bluetooth_version'] = isset($data['bluetooth_version']) ? $data['bluetooth_version'] : null;
        $this->container['ios_idfv'] = isset($data['ios_idfv']) ? $data['ios_idfv'] : null;
        $this->container['android_advertising_id'] = isset($data['android_advertising_id']) ? $data['android_advertising_id'] : null;
        $this->container['build_version_release'] = isset($data['build_version_release']) ? $data['build_version_release'] : null;
        $this->container['limit_ad_tracking'] = isset($data['limit_ad_tracking']) ? $data['limit_ad_tracking'] : null;
        $this->container['amp_id'] = isset($data['amp_id']) ? $data['amp_id'] : null;
        $this->container['is_dst'] = isset($data['is_dst']) ? $data['is_dst'] : null;
        $this->container['roku_advertising_id'] = isset($data['roku_advertising_id']) ? $data['roku_advertising_id'] : null;
        $this->container['roku_publisher_id'] = isset($data['roku_publisher_id']) ? $data['roku_publisher_id'] : null;
        $this->container['microsoft_advertising_id'] = isset($data['microsoft_advertising_id']) ? $data['microsoft_advertising_id'] : null;
        $this->container['microsoft_publisher_id'] = isset($data['microsoft_publisher_id']) ? $data['microsoft_publisher_id'] : null;
        $this->container['fire_advertising_id'] = isset($data['fire_advertising_id']) ? $data['fire_advertising_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPlatformAllowableValues();
        if (!is_null($this->container['platform']) && !in_array($this->container['platform'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'platform', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets brand
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string|null $brand brand
     *
     * @return $this
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets product
     *
     * @return string|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param string|null $product product
     *
     * @return $this
     */
    public function setProduct($product)
    {
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets device
     *
     * @return string|null
     */
    public function getDevice()
    {
        return $this->container['device'];
    }

    /**
     * Sets device
     *
     * @param string|null $device device
     *
     * @return $this
     */
    public function setDevice($device)
    {
        $this->container['device'] = $device;

        return $this;
    }

    /**
     * Gets android_uuid
     *
     * @return string|null
     */
    public function getAndroidUuid()
    {
        return $this->container['android_uuid'];
    }

    /**
     * Sets android_uuid
     *
     * @param string|null $android_uuid android_uuid
     *
     * @return $this
     */
    public function setAndroidUuid($android_uuid)
    {
        $this->container['android_uuid'] = $android_uuid;

        return $this;
    }

    /**
     * Gets device_manufacturer
     *
     * @return string|null
     */
    public function getDeviceManufacturer()
    {
        return $this->container['device_manufacturer'];
    }

    /**
     * Sets device_manufacturer
     *
     * @param string|null $device_manufacturer device_manufacturer
     *
     * @return $this
     */
    public function setDeviceManufacturer($device_manufacturer)
    {
        $this->container['device_manufacturer'] = $device_manufacturer;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string|null
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string|null $platform platform
     *
     * @return $this
     */
    public function setPlatform($platform)
    {
        $allowedValues = $this->getPlatformAllowableValues();
        if (!is_null($platform) && !in_array($platform, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'platform', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets os_version
     *
     * @return string|null
     */
    public function getOsVersion()
    {
        return $this->container['os_version'];
    }

    /**
     * Sets os_version
     *
     * @param string|null $os_version os_version
     *
     * @return $this
     */
    public function setOsVersion($os_version)
    {
        $this->container['os_version'] = $os_version;

        return $this;
    }

    /**
     * Gets device_model
     *
     * @return string|null
     */
    public function getDeviceModel()
    {
        return $this->container['device_model'];
    }

    /**
     * Sets device_model
     *
     * @param string|null $device_model device_model
     *
     * @return $this
     */
    public function setDeviceModel($device_model)
    {
        $this->container['device_model'] = $device_model;

        return $this;
    }

    /**
     * Gets screen_height
     *
     * @return int|null
     */
    public function getScreenHeight()
    {
        return $this->container['screen_height'];
    }

    /**
     * Sets screen_height
     *
     * @param int|null $screen_height screen_height
     *
     * @return $this
     */
    public function setScreenHeight($screen_height)
    {
        $this->container['screen_height'] = $screen_height;

        return $this;
    }

    /**
     * Gets screen_width
     *
     * @return int|null
     */
    public function getScreenWidth()
    {
        return $this->container['screen_width'];
    }

    /**
     * Sets screen_width
     *
     * @param int|null $screen_width screen_width
     *
     * @return $this
     */
    public function setScreenWidth($screen_width)
    {
        $this->container['screen_width'] = $screen_width;

        return $this;
    }

    /**
     * Gets screen_dpi
     *
     * @return int|null
     */
    public function getScreenDpi()
    {
        return $this->container['screen_dpi'];
    }

    /**
     * Sets screen_dpi
     *
     * @param int|null $screen_dpi screen_dpi
     *
     * @return $this
     */
    public function setScreenDpi($screen_dpi)
    {
        $this->container['screen_dpi'] = $screen_dpi;

        return $this;
    }

    /**
     * Gets device_country
     *
     * @return string|null
     */
    public function getDeviceCountry()
    {
        return $this->container['device_country'];
    }

    /**
     * Sets device_country
     *
     * @param string|null $device_country device_country
     *
     * @return $this
     */
    public function setDeviceCountry($device_country)
    {
        $this->container['device_country'] = $device_country;

        return $this;
    }

    /**
     * Gets locale_language
     *
     * @return string|null
     */
    public function getLocaleLanguage()
    {
        return $this->container['locale_language'];
    }

    /**
     * Sets locale_language
     *
     * @param string|null $locale_language locale_language
     *
     * @return $this
     */
    public function setLocaleLanguage($locale_language)
    {
        $this->container['locale_language'] = $locale_language;

        return $this;
    }

    /**
     * Gets locale_country
     *
     * @return string|null
     */
    public function getLocaleCountry()
    {
        return $this->container['locale_country'];
    }

    /**
     * Sets locale_country
     *
     * @param string|null $locale_country locale_country
     *
     * @return $this
     */
    public function setLocaleCountry($locale_country)
    {
        $this->container['locale_country'] = $locale_country;

        return $this;
    }

    /**
     * Gets network_country
     *
     * @return string|null
     */
    public function getNetworkCountry()
    {
        return $this->container['network_country'];
    }

    /**
     * Sets network_country
     *
     * @param string|null $network_country network_country
     *
     * @return $this
     */
    public function setNetworkCountry($network_country)
    {
        $this->container['network_country'] = $network_country;

        return $this;
    }

    /**
     * Gets network_carrier
     *
     * @return string|null
     */
    public function getNetworkCarrier()
    {
        return $this->container['network_carrier'];
    }

    /**
     * Sets network_carrier
     *
     * @param string|null $network_carrier network_carrier
     *
     * @return $this
     */
    public function setNetworkCarrier($network_carrier)
    {
        $this->container['network_carrier'] = $network_carrier;

        return $this;
    }

    /**
     * Gets network_code
     *
     * @return string|null
     */
    public function getNetworkCode()
    {
        return $this->container['network_code'];
    }

    /**
     * Sets network_code
     *
     * @param string|null $network_code network_code
     *
     * @return $this
     */
    public function setNetworkCode($network_code)
    {
        $this->container['network_code'] = $network_code;

        return $this;
    }

    /**
     * Gets network_mobile_country_code
     *
     * @return string|null
     */
    public function getNetworkMobileCountryCode()
    {
        return $this->container['network_mobile_country_code'];
    }

    /**
     * Sets network_mobile_country_code
     *
     * @param string|null $network_mobile_country_code network_mobile_country_code
     *
     * @return $this
     */
    public function setNetworkMobileCountryCode($network_mobile_country_code)
    {
        $this->container['network_mobile_country_code'] = $network_mobile_country_code;

        return $this;
    }

    /**
     * Gets timezone_offset
     *
     * @return int|null
     */
    public function getTimezoneOffset()
    {
        return $this->container['timezone_offset'];
    }

    /**
     * Sets timezone_offset
     *
     * @param int|null $timezone_offset timezone_offset
     *
     * @return $this
     */
    public function setTimezoneOffset($timezone_offset)
    {
        $this->container['timezone_offset'] = $timezone_offset;

        return $this;
    }

    /**
     * Gets build_identifier
     *
     * @return string|null
     */
    public function getBuildIdentifier()
    {
        return $this->container['build_identifier'];
    }

    /**
     * Sets build_identifier
     *
     * @param string|null $build_identifier build_identifier
     *
     * @return $this
     */
    public function setBuildIdentifier($build_identifier)
    {
        $this->container['build_identifier'] = $build_identifier;

        return $this;
    }

    /**
     * Gets http_header_user_agent
     *
     * @return string|null
     */
    public function getHttpHeaderUserAgent()
    {
        return $this->container['http_header_user_agent'];
    }

    /**
     * Sets http_header_user_agent
     *
     * @param string|null $http_header_user_agent http_header_user_agent
     *
     * @return $this
     */
    public function setHttpHeaderUserAgent($http_header_user_agent)
    {
        $this->container['http_header_user_agent'] = $http_header_user_agent;

        return $this;
    }

    /**
     * Gets ios_advertising_id
     *
     * @return string|null
     */
    public function getIosAdvertisingId()
    {
        return $this->container['ios_advertising_id'];
    }

    /**
     * Sets ios_advertising_id
     *
     * @param string|null $ios_advertising_id ios_advertising_id
     *
     * @return $this
     */
    public function setIosAdvertisingId($ios_advertising_id)
    {
        $this->container['ios_advertising_id'] = $ios_advertising_id;

        return $this;
    }

    /**
     * Gets push_token
     *
     * @return string|null
     */
    public function getPushToken()
    {
        return $this->container['push_token'];
    }

    /**
     * Sets push_token
     *
     * @param string|null $push_token push_token
     *
     * @return $this
     */
    public function setPushToken($push_token)
    {
        $this->container['push_token'] = $push_token;

        return $this;
    }

    /**
     * Gets cpu_architecture
     *
     * @return string|null
     */
    public function getCpuArchitecture()
    {
        return $this->container['cpu_architecture'];
    }

    /**
     * Sets cpu_architecture
     *
     * @param string|null $cpu_architecture cpu_architecture
     *
     * @return $this
     */
    public function setCpuArchitecture($cpu_architecture)
    {
        $this->container['cpu_architecture'] = $cpu_architecture;

        return $this;
    }

    /**
     * Gets is_tablet
     *
     * @return bool|null
     */
    public function getIsTablet()
    {
        return $this->container['is_tablet'];
    }

    /**
     * Sets is_tablet
     *
     * @param bool|null $is_tablet is_tablet
     *
     * @return $this
     */
    public function setIsTablet($is_tablet)
    {
        $this->container['is_tablet'] = $is_tablet;

        return $this;
    }

    /**
     * Gets push_notification_sound_enabled
     *
     * @return bool|null
     */
    public function getPushNotificationSoundEnabled()
    {
        return $this->container['push_notification_sound_enabled'];
    }

    /**
     * Sets push_notification_sound_enabled
     *
     * @param bool|null $push_notification_sound_enabled push_notification_sound_enabled
     *
     * @return $this
     */
    public function setPushNotificationSoundEnabled($push_notification_sound_enabled)
    {
        $this->container['push_notification_sound_enabled'] = $push_notification_sound_enabled;

        return $this;
    }

    /**
     * Gets push_notification_vibrate_enabled
     *
     * @return bool|null
     */
    public function getPushNotificationVibrateEnabled()
    {
        return $this->container['push_notification_vibrate_enabled'];
    }

    /**
     * Sets push_notification_vibrate_enabled
     *
     * @param bool|null $push_notification_vibrate_enabled push_notification_vibrate_enabled
     *
     * @return $this
     */
    public function setPushNotificationVibrateEnabled($push_notification_vibrate_enabled)
    {
        $this->container['push_notification_vibrate_enabled'] = $push_notification_vibrate_enabled;

        return $this;
    }

    /**
     * Gets radio_access_technology
     *
     * @return string|null
     */
    public function getRadioAccessTechnology()
    {
        return $this->container['radio_access_technology'];
    }

    /**
     * Sets radio_access_technology
     *
     * @param string|null $radio_access_technology radio_access_technology
     *
     * @return $this
     */
    public function setRadioAccessTechnology($radio_access_technology)
    {
        $this->container['radio_access_technology'] = $radio_access_technology;

        return $this;
    }

    /**
     * Gets supports_telephony
     *
     * @return bool|null
     */
    public function getSupportsTelephony()
    {
        return $this->container['supports_telephony'];
    }

    /**
     * Sets supports_telephony
     *
     * @param bool|null $supports_telephony supports_telephony
     *
     * @return $this
     */
    public function setSupportsTelephony($supports_telephony)
    {
        $this->container['supports_telephony'] = $supports_telephony;

        return $this;
    }

    /**
     * Gets has_nfc
     *
     * @return bool|null
     */
    public function getHasNfc()
    {
        return $this->container['has_nfc'];
    }

    /**
     * Sets has_nfc
     *
     * @param bool|null $has_nfc has_nfc
     *
     * @return $this
     */
    public function setHasNfc($has_nfc)
    {
        $this->container['has_nfc'] = $has_nfc;

        return $this;
    }

    /**
     * Gets bluetooth_enabled
     *
     * @return bool|null
     */
    public function getBluetoothEnabled()
    {
        return $this->container['bluetooth_enabled'];
    }

    /**
     * Sets bluetooth_enabled
     *
     * @param bool|null $bluetooth_enabled bluetooth_enabled
     *
     * @return $this
     */
    public function setBluetoothEnabled($bluetooth_enabled)
    {
        $this->container['bluetooth_enabled'] = $bluetooth_enabled;

        return $this;
    }

    /**
     * Gets bluetooth_version
     *
     * @return string|null
     */
    public function getBluetoothVersion()
    {
        return $this->container['bluetooth_version'];
    }

    /**
     * Sets bluetooth_version
     *
     * @param string|null $bluetooth_version bluetooth_version
     *
     * @return $this
     */
    public function setBluetoothVersion($bluetooth_version)
    {
        $this->container['bluetooth_version'] = $bluetooth_version;

        return $this;
    }

    /**
     * Gets ios_idfv
     *
     * @return string|null
     */
    public function getIosIdfv()
    {
        return $this->container['ios_idfv'];
    }

    /**
     * Sets ios_idfv
     *
     * @param string|null $ios_idfv ios_idfv
     *
     * @return $this
     */
    public function setIosIdfv($ios_idfv)
    {
        $this->container['ios_idfv'] = $ios_idfv;

        return $this;
    }

    /**
     * Gets android_advertising_id
     *
     * @return string|null
     */
    public function getAndroidAdvertisingId()
    {
        return $this->container['android_advertising_id'];
    }

    /**
     * Sets android_advertising_id
     *
     * @param string|null $android_advertising_id android_advertising_id
     *
     * @return $this
     */
    public function setAndroidAdvertisingId($android_advertising_id)
    {
        $this->container['android_advertising_id'] = $android_advertising_id;

        return $this;
    }

    /**
     * Gets build_version_release
     *
     * @return string|null
     */
    public function getBuildVersionRelease()
    {
        return $this->container['build_version_release'];
    }

    /**
     * Sets build_version_release
     *
     * @param string|null $build_version_release build_version_release
     *
     * @return $this
     */
    public function setBuildVersionRelease($build_version_release)
    {
        $this->container['build_version_release'] = $build_version_release;

        return $this;
    }

    /**
     * Gets limit_ad_tracking
     *
     * @return bool|null
     */
    public function getLimitAdTracking()
    {
        return $this->container['limit_ad_tracking'];
    }

    /**
     * Sets limit_ad_tracking
     *
     * @param bool|null $limit_ad_tracking limit_ad_tracking
     *
     * @return $this
     */
    public function setLimitAdTracking($limit_ad_tracking)
    {
        $this->container['limit_ad_tracking'] = $limit_ad_tracking;

        return $this;
    }

    /**
     * Gets amp_id
     *
     * @return string|null
     */
    public function getAmpId()
    {
        return $this->container['amp_id'];
    }

    /**
     * Sets amp_id
     *
     * @param string|null $amp_id amp_id
     *
     * @return $this
     */
    public function setAmpId($amp_id)
    {
        $this->container['amp_id'] = $amp_id;

        return $this;
    }

    /**
     * Gets is_dst
     *
     * @return bool|null
     */
    public function getIsDst()
    {
        return $this->container['is_dst'];
    }

    /**
     * Sets is_dst
     *
     * @param bool|null $is_dst is_dst
     *
     * @return $this
     */
    public function setIsDst($is_dst)
    {
        $this->container['is_dst'] = $is_dst;

        return $this;
    }

    /**
     * Gets roku_advertising_id
     *
     * @return string|null
     */
    public function getRokuAdvertisingId()
    {
        return $this->container['roku_advertising_id'];
    }

    /**
     * Sets roku_advertising_id
     *
     * @param string|null $roku_advertising_id roku_advertising_id
     *
     * @return $this
     */
    public function setRokuAdvertisingId($roku_advertising_id)
    {
        $this->container['roku_advertising_id'] = $roku_advertising_id;

        return $this;
    }

    /**
     * Gets roku_publisher_id
     *
     * @return string|null
     */
    public function getRokuPublisherId()
    {
        return $this->container['roku_publisher_id'];
    }

    /**
     * Sets roku_publisher_id
     *
     * @param string|null $roku_publisher_id roku_publisher_id
     *
     * @return $this
     */
    public function setRokuPublisherId($roku_publisher_id)
    {
        $this->container['roku_publisher_id'] = $roku_publisher_id;

        return $this;
    }

    /**
     * Gets microsoft_advertising_id
     *
     * @return string|null
     */
    public function getMicrosoftAdvertisingId()
    {
        return $this->container['microsoft_advertising_id'];
    }

    /**
     * Sets microsoft_advertising_id
     *
     * @param string|null $microsoft_advertising_id microsoft_advertising_id
     *
     * @return $this
     */
    public function setMicrosoftAdvertisingId($microsoft_advertising_id)
    {
        $this->container['microsoft_advertising_id'] = $microsoft_advertising_id;

        return $this;
    }

    /**
     * Gets microsoft_publisher_id
     *
     * @return string|null
     */
    public function getMicrosoftPublisherId()
    {
        return $this->container['microsoft_publisher_id'];
    }

    /**
     * Sets microsoft_publisher_id
     *
     * @param string|null $microsoft_publisher_id microsoft_publisher_id
     *
     * @return $this
     */
    public function setMicrosoftPublisherId($microsoft_publisher_id)
    {
        $this->container['microsoft_publisher_id'] = $microsoft_publisher_id;

        return $this;
    }

    /**
     * Gets fire_advertising_id
     *
     * @return string|null
     */
    public function getFireAdvertisingId()
    {
        return $this->container['fire_advertising_id'];
    }

    /**
     * Sets fire_advertising_id
     *
     * @param string|null $fire_advertising_id fire_advertising_id
     *
     * @return $this
     */
    public function setFireAdvertisingId($fire_advertising_id)
    {
        $this->container['fire_advertising_id'] = $fire_advertising_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


