<?php
/**
 * EventType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EventType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventType
{
    /**
     * Possible values of this enum
     */
    const SESSION_START = 'session_start';
    const SESSION_END = 'session_end';
    const SCREEN_VIEW = 'screen_view';
    const CUSTOM_EVENT = 'custom_event';
    const CRASH_REPORT = 'crash_report';
    const OPT_OUT = 'opt_out';
    const FIRST_RUN = 'first_run';
    const PRE_ATTRIBUTION = 'pre_attribution';
    const PUSH_REGISTRATION = 'push_registration';
    const APPLICATION_STATE_TRANSITION = 'application_state_transition';
    const PUSH_MESSAGE = 'push_message';
    const NETWORK_PERFORMANCE = 'network_performance';
    const BREADCRUMB = 'breadcrumb';
    const PROFILE = 'profile';
    const PUSH_REACTION = 'push_reaction';
    const COMMERCE_EVENT = 'commerce_event';
    const USER_ATTRIBUTE_CHANGE = 'user_attribute_change';
    const USER_IDENTITY_CHANGE = 'user_identity_change';
    const UNINSTALL = 'uninstall';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SESSION_START,
            self::SESSION_END,
            self::SCREEN_VIEW,
            self::CUSTOM_EVENT,
            self::CRASH_REPORT,
            self::OPT_OUT,
            self::FIRST_RUN,
            self::PRE_ATTRIBUTION,
            self::PUSH_REGISTRATION,
            self::APPLICATION_STATE_TRANSITION,
            self::PUSH_MESSAGE,
            self::NETWORK_PERFORMANCE,
            self::BREADCRUMB,
            self::PROFILE,
            self::PUSH_REACTION,
            self::COMMERCE_EVENT,
            self::USER_ATTRIBUTE_CHANGE,
            self::USER_IDENTITY_CHANGE,
            self::UNINSTALL,
        ];
    }
}


