<?php
/**
 * GDPRConsentState
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GDPRConsentState Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GDPRConsentState implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GDPRConsentState';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'regulation' => 'string',
        'document' => 'string',
        'consented' => 'bool',
        'timestamp_unixtime_ms' => 'int',
        'location' => 'string',
        'hardware_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'regulation' => null,
        'document' => null,
        'consented' => null,
        'timestamp_unixtime_ms' => null,
        'location' => null,
        'hardware_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'regulation' => 'regulation',
        'document' => 'document',
        'consented' => 'consented',
        'timestamp_unixtime_ms' => 'timestamp_unixtime_ms',
        'location' => 'location',
        'hardware_id' => 'hardware_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'regulation' => 'setRegulation',
        'document' => 'setDocument',
        'consented' => 'setConsented',
        'timestamp_unixtime_ms' => 'setTimestampUnixtimeMs',
        'location' => 'setLocation',
        'hardware_id' => 'setHardwareId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'regulation' => 'getRegulation',
        'document' => 'getDocument',
        'consented' => 'getConsented',
        'timestamp_unixtime_ms' => 'getTimestampUnixtimeMs',
        'location' => 'getLocation',
        'hardware_id' => 'getHardwareId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['regulation'] = isset($data['regulation']) ? $data['regulation'] : null;
        $this->container['document'] = isset($data['document']) ? $data['document'] : null;
        $this->container['consented'] = isset($data['consented']) ? $data['consented'] : null;
        $this->container['timestamp_unixtime_ms'] = isset($data['timestamp_unixtime_ms']) ? $data['timestamp_unixtime_ms'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['hardware_id'] = isset($data['hardware_id']) ? $data['hardware_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['regulation'] === null) {
            $invalidProperties[] = "'regulation' can't be null";
        }
        if ($this->container['document'] === null) {
            $invalidProperties[] = "'document' can't be null";
        }
        if ($this->container['consented'] === null) {
            $invalidProperties[] = "'consented' can't be null";
        }
        if ($this->container['timestamp_unixtime_ms'] === null) {
            $invalidProperties[] = "'timestamp_unixtime_ms' can't be null";
        }
        if ($this->container['location'] === null) {
            $invalidProperties[] = "'location' can't be null";
        }
        if ($this->container['hardware_id'] === null) {
            $invalidProperties[] = "'hardware_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets regulation
     *
     * @return string
     */
    public function getRegulation()
    {
        return $this->container['regulation'];
    }

    /**
     * Sets regulation
     *
     * @param string $regulation regulation
     *
     * @return $this
     */
    public function setRegulation($regulation)
    {
        $this->container['regulation'] = $regulation;

        return $this;
    }

    /**
     * Gets document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->container['document'];
    }

    /**
     * Sets document
     *
     * @param string $document document
     *
     * @return $this
     */
    public function setDocument($document)
    {
        $this->container['document'] = $document;

        return $this;
    }

    /**
     * Gets consented
     *
     * @return bool
     */
    public function getConsented()
    {
        return $this->container['consented'];
    }

    /**
     * Sets consented
     *
     * @param bool $consented consented
     *
     * @return $this
     */
    public function setConsented($consented)
    {
        $this->container['consented'] = $consented;

        return $this;
    }

    /**
     * Gets timestamp_unixtime_ms
     *
     * @return int
     */
    public function getTimestampUnixtimeMs()
    {
        return $this->container['timestamp_unixtime_ms'];
    }

    /**
     * Sets timestamp_unixtime_ms
     *
     * @param int $timestamp_unixtime_ms timestamp_unixtime_ms
     *
     * @return $this
     */
    public function setTimestampUnixtimeMs($timestamp_unixtime_ms)
    {
        $this->container['timestamp_unixtime_ms'] = $timestamp_unixtime_ms;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets hardware_id
     *
     * @return string
     */
    public function getHardwareId()
    {
        return $this->container['hardware_id'];
    }

    /**
     * Sets hardware_id
     *
     * @param string $hardware_id hardware_id
     *
     * @return $this
     */
    public function setHardwareId($hardware_id)
    {
        $this->container['hardware_id'] = $hardware_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


