<?php
/**
 * IdentityType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * IdentityType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IdentityType
{
    /**
     * Possible values of this enum
     */
    const OTHER = 'other';
    const CUSTOMER_ID = 'customer_id';
    const FACEBOOK = 'facebook';
    const TWITTER = 'twitter';
    const GOOGLE = 'google';
    const MICROSOFT = 'microsoft';
    const YAHOO = 'yahoo';
    const EMAIL = 'email';
    const ALIAS = 'alias';
    const FACEBOOK_CUSTOM_AUDIENCE_ID = 'facebook_custom_audience_id';
    const OTHER_ID_2 = 'other_id_2';
    const OTHER_ID_3 = 'other_id_3';
    const OTHER_ID_4 = 'other_id_4';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OTHER,
            self::CUSTOMER_ID,
            self::FACEBOOK,
            self::TWITTER,
            self::GOOGLE,
            self::MICROSOFT,
            self::YAHOO,
            self::EMAIL,
            self::ALIAS,
            self::FACEBOOK_CUSTOM_AUDIENCE_ID,
            self::OTHER_ID_2,
            self::OTHER_ID_3,
            self::OTHER_ID_4,
        ];
    }
}


