<?php
/**
 * NetworkPerformanceEventDataAllOf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * NetworkPerformanceEventDataAllOf Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NetworkPerformanceEventDataAllOf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NetworkPerformanceEventData_allOf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'http_verb' => 'string',
        'url' => 'string',
        'time_elapsed' => 'int',
        'bytes_in' => 'int',
        'bytes_out' => 'int',
        'response_code' => 'int',
        'data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'http_verb' => null,
        'url' => null,
        'time_elapsed' => null,
        'bytes_in' => null,
        'bytes_out' => null,
        'response_code' => null,
        'data' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'http_verb' => 'http_verb',
        'url' => 'url',
        'time_elapsed' => 'time_elapsed',
        'bytes_in' => 'bytes_in',
        'bytes_out' => 'bytes_out',
        'response_code' => 'response_code',
        'data' => 'data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'http_verb' => 'setHttpVerb',
        'url' => 'setUrl',
        'time_elapsed' => 'setTimeElapsed',
        'bytes_in' => 'setBytesIn',
        'bytes_out' => 'setBytesOut',
        'response_code' => 'setResponseCode',
        'data' => 'setData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'http_verb' => 'getHttpVerb',
        'url' => 'getUrl',
        'time_elapsed' => 'getTimeElapsed',
        'bytes_in' => 'getBytesIn',
        'bytes_out' => 'getBytesOut',
        'response_code' => 'getResponseCode',
        'data' => 'getData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['http_verb'] = isset($data['http_verb']) ? $data['http_verb'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['time_elapsed'] = isset($data['time_elapsed']) ? $data['time_elapsed'] : null;
        $this->container['bytes_in'] = isset($data['bytes_in']) ? $data['bytes_in'] : null;
        $this->container['bytes_out'] = isset($data['bytes_out']) ? $data['bytes_out'] : null;
        $this->container['response_code'] = isset($data['response_code']) ? $data['response_code'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['response_code'] === null) {
            $invalidProperties[] = "'response_code' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets http_verb
     *
     * @return string|null
     */
    public function getHttpVerb()
    {
        return $this->container['http_verb'];
    }

    /**
     * Sets http_verb
     *
     * @param string|null $http_verb http_verb
     *
     * @return $this
     */
    public function setHttpVerb($http_verb)
    {
        $this->container['http_verb'] = $http_verb;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets time_elapsed
     *
     * @return int|null
     */
    public function getTimeElapsed()
    {
        return $this->container['time_elapsed'];
    }

    /**
     * Sets time_elapsed
     *
     * @param int|null $time_elapsed time_elapsed
     *
     * @return $this
     */
    public function setTimeElapsed($time_elapsed)
    {
        $this->container['time_elapsed'] = $time_elapsed;

        return $this;
    }

    /**
     * Gets bytes_in
     *
     * @return int|null
     */
    public function getBytesIn()
    {
        return $this->container['bytes_in'];
    }

    /**
     * Sets bytes_in
     *
     * @param int|null $bytes_in bytes_in
     *
     * @return $this
     */
    public function setBytesIn($bytes_in)
    {
        $this->container['bytes_in'] = $bytes_in;

        return $this;
    }

    /**
     * Gets bytes_out
     *
     * @return int|null
     */
    public function getBytesOut()
    {
        return $this->container['bytes_out'];
    }

    /**
     * Sets bytes_out
     *
     * @param int|null $bytes_out bytes_out
     *
     * @return $this
     */
    public function setBytesOut($bytes_out)
    {
        $this->container['bytes_out'] = $bytes_out;

        return $this;
    }

    /**
     * Gets response_code
     *
     * @return int
     */
    public function getResponseCode()
    {
        return $this->container['response_code'];
    }

    /**
     * Sets response_code
     *
     * @param int $response_code response_code
     *
     * @return $this
     */
    public function setResponseCode($response_code)
    {
        $this->container['response_code'] = $response_code;

        return $this;
    }

    /**
     * Gets data
     *
     * @return string|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param string|null $data data
     *
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


