<?php
/**
 * ProductAction
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProductAction Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductAction implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductAction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'action' => 'string',
        'checkout_step' => 'int',
        'checkout_options' => 'string',
        'product_action_list' => 'string',
        'product_list_source' => 'string',
        'transaction_id' => 'string',
        'affiliation' => 'string',
        'total_amount' => 'float',
        'tax_amount' => 'float',
        'shipping_amount' => 'float',
        'coupon_code' => 'string',
        'products' => '\OpenAPI\Client\Model\Product[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'action' => null,
        'checkout_step' => null,
        'checkout_options' => null,
        'product_action_list' => null,
        'product_list_source' => null,
        'transaction_id' => null,
        'affiliation' => null,
        'total_amount' => null,
        'tax_amount' => null,
        'shipping_amount' => null,
        'coupon_code' => null,
        'products' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action' => 'action',
        'checkout_step' => 'checkout_step',
        'checkout_options' => 'checkout_options',
        'product_action_list' => 'product_action_list',
        'product_list_source' => 'product_list_source',
        'transaction_id' => 'transaction_id',
        'affiliation' => 'affiliation',
        'total_amount' => 'total_amount',
        'tax_amount' => 'tax_amount',
        'shipping_amount' => 'shipping_amount',
        'coupon_code' => 'coupon_code',
        'products' => 'products'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action' => 'setAction',
        'checkout_step' => 'setCheckoutStep',
        'checkout_options' => 'setCheckoutOptions',
        'product_action_list' => 'setProductActionList',
        'product_list_source' => 'setProductListSource',
        'transaction_id' => 'setTransactionId',
        'affiliation' => 'setAffiliation',
        'total_amount' => 'setTotalAmount',
        'tax_amount' => 'setTaxAmount',
        'shipping_amount' => 'setShippingAmount',
        'coupon_code' => 'setCouponCode',
        'products' => 'setProducts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action' => 'getAction',
        'checkout_step' => 'getCheckoutStep',
        'checkout_options' => 'getCheckoutOptions',
        'product_action_list' => 'getProductActionList',
        'product_list_source' => 'getProductListSource',
        'transaction_id' => 'getTransactionId',
        'affiliation' => 'getAffiliation',
        'total_amount' => 'getTotalAmount',
        'tax_amount' => 'getTaxAmount',
        'shipping_amount' => 'getShippingAmount',
        'coupon_code' => 'getCouponCode',
        'products' => 'getProducts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const ACTION_ADD_TO_CART = 'add_to_cart';
    const ACTION_REMOVE_FROM_CART = 'remove_from_cart';
    const ACTION_CHECKOUT = 'checkout';
    const ACTION_CHECKOUT_OPTION = 'checkout_option';
    const ACTION_CLICK = 'click';
    const ACTION_VIEW_DETAIL = 'view_detail';
    const ACTION_PURCHASE = 'purchase';
    const ACTION_REFUND = 'refund';
    const ACTION_ADD_TO_WISHLIST = 'add_to_wishlist';
    const ACTION_REMOVE_FROM_WISH_LIST = 'remove_from_wish_list';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues()
    {
        return [
            self::ACTION_ADD_TO_CART,
            self::ACTION_REMOVE_FROM_CART,
            self::ACTION_CHECKOUT,
            self::ACTION_CHECKOUT_OPTION,
            self::ACTION_CLICK,
            self::ACTION_VIEW_DETAIL,
            self::ACTION_PURCHASE,
            self::ACTION_REFUND,
            self::ACTION_ADD_TO_WISHLIST,
            self::ACTION_REMOVE_FROM_WISH_LIST,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['action'] = isset($data['action']) ? $data['action'] : null;
        $this->container['checkout_step'] = isset($data['checkout_step']) ? $data['checkout_step'] : null;
        $this->container['checkout_options'] = isset($data['checkout_options']) ? $data['checkout_options'] : null;
        $this->container['product_action_list'] = isset($data['product_action_list']) ? $data['product_action_list'] : null;
        $this->container['product_list_source'] = isset($data['product_list_source']) ? $data['product_list_source'] : null;
        $this->container['transaction_id'] = isset($data['transaction_id']) ? $data['transaction_id'] : null;
        $this->container['affiliation'] = isset($data['affiliation']) ? $data['affiliation'] : null;
        $this->container['total_amount'] = isset($data['total_amount']) ? $data['total_amount'] : null;
        $this->container['tax_amount'] = isset($data['tax_amount']) ? $data['tax_amount'] : null;
        $this->container['shipping_amount'] = isset($data['shipping_amount']) ? $data['shipping_amount'] : null;
        $this->container['coupon_code'] = isset($data['coupon_code']) ? $data['coupon_code'] : null;
        $this->container['products'] = isset($data['products']) ? $data['products'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['action'] === null) {
            $invalidProperties[] = "'action' can't be null";
        }
        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['action']) && !in_array($this->container['action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'action', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['checkout_step'] === null) {
            $invalidProperties[] = "'checkout_step' can't be null";
        }
        if ($this->container['checkout_options'] === null) {
            $invalidProperties[] = "'checkout_options' can't be null";
        }
        if ($this->container['product_action_list'] === null) {
            $invalidProperties[] = "'product_action_list' can't be null";
        }
        if ($this->container['product_list_source'] === null) {
            $invalidProperties[] = "'product_list_source' can't be null";
        }
        if ($this->container['transaction_id'] === null) {
            $invalidProperties[] = "'transaction_id' can't be null";
        }
        if ($this->container['affiliation'] === null) {
            $invalidProperties[] = "'affiliation' can't be null";
        }
        if ($this->container['total_amount'] === null) {
            $invalidProperties[] = "'total_amount' can't be null";
        }
        if ($this->container['tax_amount'] === null) {
            $invalidProperties[] = "'tax_amount' can't be null";
        }
        if ($this->container['shipping_amount'] === null) {
            $invalidProperties[] = "'shipping_amount' can't be null";
        }
        if ($this->container['coupon_code'] === null) {
            $invalidProperties[] = "'coupon_code' can't be null";
        }
        if ($this->container['products'] === null) {
            $invalidProperties[] = "'products' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action
     *
     * @return string
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string $action action
     *
     * @return $this
     */
    public function setAction($action)
    {
        $allowedValues = $this->getActionAllowableValues();
        if (!in_array($action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'action', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets checkout_step
     *
     * @return int
     */
    public function getCheckoutStep()
    {
        return $this->container['checkout_step'];
    }

    /**
     * Sets checkout_step
     *
     * @param int $checkout_step checkout_step
     *
     * @return $this
     */
    public function setCheckoutStep($checkout_step)
    {
        $this->container['checkout_step'] = $checkout_step;

        return $this;
    }

    /**
     * Gets checkout_options
     *
     * @return string
     */
    public function getCheckoutOptions()
    {
        return $this->container['checkout_options'];
    }

    /**
     * Sets checkout_options
     *
     * @param string $checkout_options checkout_options
     *
     * @return $this
     */
    public function setCheckoutOptions($checkout_options)
    {
        $this->container['checkout_options'] = $checkout_options;

        return $this;
    }

    /**
     * Gets product_action_list
     *
     * @return string
     */
    public function getProductActionList()
    {
        return $this->container['product_action_list'];
    }

    /**
     * Sets product_action_list
     *
     * @param string $product_action_list product_action_list
     *
     * @return $this
     */
    public function setProductActionList($product_action_list)
    {
        $this->container['product_action_list'] = $product_action_list;

        return $this;
    }

    /**
     * Gets product_list_source
     *
     * @return string
     */
    public function getProductListSource()
    {
        return $this->container['product_list_source'];
    }

    /**
     * Sets product_list_source
     *
     * @param string $product_list_source product_list_source
     *
     * @return $this
     */
    public function setProductListSource($product_list_source)
    {
        $this->container['product_list_source'] = $product_list_source;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string $transaction_id transaction_id
     *
     * @return $this
     */
    public function setTransactionId($transaction_id)
    {
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets affiliation
     *
     * @return string
     */
    public function getAffiliation()
    {
        return $this->container['affiliation'];
    }

    /**
     * Sets affiliation
     *
     * @param string $affiliation affiliation
     *
     * @return $this
     */
    public function setAffiliation($affiliation)
    {
        $this->container['affiliation'] = $affiliation;

        return $this;
    }

    /**
     * Gets total_amount
     *
     * @return float
     */
    public function getTotalAmount()
    {
        return $this->container['total_amount'];
    }

    /**
     * Sets total_amount
     *
     * @param float $total_amount total_amount
     *
     * @return $this
     */
    public function setTotalAmount($total_amount)
    {
        $this->container['total_amount'] = $total_amount;

        return $this;
    }

    /**
     * Gets tax_amount
     *
     * @return float
     */
    public function getTaxAmount()
    {
        return $this->container['tax_amount'];
    }

    /**
     * Sets tax_amount
     *
     * @param float $tax_amount tax_amount
     *
     * @return $this
     */
    public function setTaxAmount($tax_amount)
    {
        $this->container['tax_amount'] = $tax_amount;

        return $this;
    }

    /**
     * Gets shipping_amount
     *
     * @return float
     */
    public function getShippingAmount()
    {
        return $this->container['shipping_amount'];
    }

    /**
     * Sets shipping_amount
     *
     * @param float $shipping_amount shipping_amount
     *
     * @return $this
     */
    public function setShippingAmount($shipping_amount)
    {
        $this->container['shipping_amount'] = $shipping_amount;

        return $this;
    }

    /**
     * Gets coupon_code
     *
     * @return string
     */
    public function getCouponCode()
    {
        return $this->container['coupon_code'];
    }

    /**
     * Sets coupon_code
     *
     * @param string $coupon_code coupon_code
     *
     * @return $this
     */
    public function setCouponCode($coupon_code)
    {
        $this->container['coupon_code'] = $coupon_code;

        return $this;
    }

    /**
     * Gets products
     *
     * @return \OpenAPI\Client\Model\Product[]
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     *
     * @param \OpenAPI\Client\Model\Product[] $products products
     *
     * @return $this
     */
    public function setProducts($products)
    {
        $this->container['products'] = $products;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


