<?php
/**
 * ProfileEventDataAllOf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProfileEventDataAllOf Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProfileEventDataAllOf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProfileEventData_allOf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'previous_mpid' => 'int',
        'current_mpid' => 'int',
        'profile_event_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'previous_mpid' => null,
        'current_mpid' => null,
        'profile_event_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'previous_mpid' => 'previous_mpid',
        'current_mpid' => 'current_mpid',
        'profile_event_type' => 'profile_event_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'previous_mpid' => 'setPreviousMpid',
        'current_mpid' => 'setCurrentMpid',
        'profile_event_type' => 'setProfileEventType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'previous_mpid' => 'getPreviousMpid',
        'current_mpid' => 'getCurrentMpid',
        'profile_event_type' => 'getProfileEventType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const PROFILE_EVENT_TYPE_SIGNUP = 'signup';
    const PROFILE_EVENT_TYPE_LOGIN = 'login';
    const PROFILE_EVENT_TYPE_LOGOUT = 'logout';
    const PROFILE_EVENT_TYPE_UPDATE = 'update';
    const PROFILE_EVENT_TYPE_DELETE = 'delete';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProfileEventTypeAllowableValues()
    {
        return [
            self::PROFILE_EVENT_TYPE_SIGNUP,
            self::PROFILE_EVENT_TYPE_LOGIN,
            self::PROFILE_EVENT_TYPE_LOGOUT,
            self::PROFILE_EVENT_TYPE_UPDATE,
            self::PROFILE_EVENT_TYPE_DELETE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['previous_mpid'] = isset($data['previous_mpid']) ? $data['previous_mpid'] : null;
        $this->container['current_mpid'] = isset($data['current_mpid']) ? $data['current_mpid'] : null;
        $this->container['profile_event_type'] = isset($data['profile_event_type']) ? $data['profile_event_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['previous_mpid'] === null) {
            $invalidProperties[] = "'previous_mpid' can't be null";
        }
        if ($this->container['current_mpid'] === null) {
            $invalidProperties[] = "'current_mpid' can't be null";
        }
        if ($this->container['profile_event_type'] === null) {
            $invalidProperties[] = "'profile_event_type' can't be null";
        }
        $allowedValues = $this->getProfileEventTypeAllowableValues();
        if (!is_null($this->container['profile_event_type']) && !in_array($this->container['profile_event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'profile_event_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets previous_mpid
     *
     * @return int
     */
    public function getPreviousMpid()
    {
        return $this->container['previous_mpid'];
    }

    /**
     * Sets previous_mpid
     *
     * @param int $previous_mpid previous_mpid
     *
     * @return $this
     */
    public function setPreviousMpid($previous_mpid)
    {
        $this->container['previous_mpid'] = $previous_mpid;

        return $this;
    }

    /**
     * Gets current_mpid
     *
     * @return int
     */
    public function getCurrentMpid()
    {
        return $this->container['current_mpid'];
    }

    /**
     * Sets current_mpid
     *
     * @param int $current_mpid current_mpid
     *
     * @return $this
     */
    public function setCurrentMpid($current_mpid)
    {
        $this->container['current_mpid'] = $current_mpid;

        return $this;
    }

    /**
     * Gets profile_event_type
     *
     * @return string
     */
    public function getProfileEventType()
    {
        return $this->container['profile_event_type'];
    }

    /**
     * Sets profile_event_type
     *
     * @param string $profile_event_type profile_event_type
     *
     * @return $this
     */
    public function setProfileEventType($profile_event_type)
    {
        $allowedValues = $this->getProfileEventTypeAllowableValues();
        if (!in_array($profile_event_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'profile_event_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['profile_event_type'] = $profile_event_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


