<?php
/**
 * PushMessageEventDataAllOf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PushMessageEventDataAllOf Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PushMessageEventDataAllOf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PushMessageEventData_allOf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'push_message_token' => 'string',
        'push_message_type' => 'string',
        'message' => 'string',
        'network' => 'string',
        'push_notification_payload' => 'string',
        'application_state' => 'string',
        'action_identifier' => 'string',
        'push_message_behavior' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'push_message_token' => null,
        'push_message_type' => null,
        'message' => null,
        'network' => null,
        'push_notification_payload' => null,
        'application_state' => null,
        'action_identifier' => null,
        'push_message_behavior' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'push_message_token' => 'push_message_token',
        'push_message_type' => 'push_message_type',
        'message' => 'message',
        'network' => 'network',
        'push_notification_payload' => 'push_notification_payload',
        'application_state' => 'application_state',
        'action_identifier' => 'action_identifier',
        'push_message_behavior' => 'push_message_behavior'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'push_message_token' => 'setPushMessageToken',
        'push_message_type' => 'setPushMessageType',
        'message' => 'setMessage',
        'network' => 'setNetwork',
        'push_notification_payload' => 'setPushNotificationPayload',
        'application_state' => 'setApplicationState',
        'action_identifier' => 'setActionIdentifier',
        'push_message_behavior' => 'setPushMessageBehavior'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'push_message_token' => 'getPushMessageToken',
        'push_message_type' => 'getPushMessageType',
        'message' => 'getMessage',
        'network' => 'getNetwork',
        'push_notification_payload' => 'getPushNotificationPayload',
        'application_state' => 'getApplicationState',
        'action_identifier' => 'getActionIdentifier',
        'push_message_behavior' => 'getPushMessageBehavior'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const PUSH_MESSAGE_TYPE_SENT = 'sent';
    const PUSH_MESSAGE_TYPE_RECEIVED = 'received';
    const PUSH_MESSAGE_TYPE_ACTION = 'action';
    const APPLICATION_STATE_NOT_RUNNING = 'not_running';
    const APPLICATION_STATE_BACKGROUND = 'background';
    const APPLICATION_STATE_FOREGROUND = 'foreground';
    const PUSH_MESSAGE_BEHAVIOR_RECEIVED = 'Received';
    const PUSH_MESSAGE_BEHAVIOR_DIRECT_OPEN = 'DirectOpen';
    const PUSH_MESSAGE_BEHAVIOR_READ = 'Read';
    const PUSH_MESSAGE_BEHAVIOR_INFLUENCED_OPEN = 'InfluencedOpen';
    const PUSH_MESSAGE_BEHAVIOR_DISPLAYED = 'Displayed';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPushMessageTypeAllowableValues()
    {
        return [
            self::PUSH_MESSAGE_TYPE_SENT,
            self::PUSH_MESSAGE_TYPE_RECEIVED,
            self::PUSH_MESSAGE_TYPE_ACTION,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplicationStateAllowableValues()
    {
        return [
            self::APPLICATION_STATE_NOT_RUNNING,
            self::APPLICATION_STATE_BACKGROUND,
            self::APPLICATION_STATE_FOREGROUND,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPushMessageBehaviorAllowableValues()
    {
        return [
            self::PUSH_MESSAGE_BEHAVIOR_RECEIVED,
            self::PUSH_MESSAGE_BEHAVIOR_DIRECT_OPEN,
            self::PUSH_MESSAGE_BEHAVIOR_READ,
            self::PUSH_MESSAGE_BEHAVIOR_INFLUENCED_OPEN,
            self::PUSH_MESSAGE_BEHAVIOR_DISPLAYED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['push_message_token'] = isset($data['push_message_token']) ? $data['push_message_token'] : null;
        $this->container['push_message_type'] = isset($data['push_message_type']) ? $data['push_message_type'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['network'] = isset($data['network']) ? $data['network'] : null;
        $this->container['push_notification_payload'] = isset($data['push_notification_payload']) ? $data['push_notification_payload'] : null;
        $this->container['application_state'] = isset($data['application_state']) ? $data['application_state'] : null;
        $this->container['action_identifier'] = isset($data['action_identifier']) ? $data['action_identifier'] : null;
        $this->container['push_message_behavior'] = isset($data['push_message_behavior']) ? $data['push_message_behavior'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['push_message_token'] === null) {
            $invalidProperties[] = "'push_message_token' can't be null";
        }
        if ($this->container['push_message_type'] === null) {
            $invalidProperties[] = "'push_message_type' can't be null";
        }
        $allowedValues = $this->getPushMessageTypeAllowableValues();
        if (!is_null($this->container['push_message_type']) && !in_array($this->container['push_message_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'push_message_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['push_notification_payload'] === null) {
            $invalidProperties[] = "'push_notification_payload' can't be null";
        }
        $allowedValues = $this->getApplicationStateAllowableValues();
        if (!is_null($this->container['application_state']) && !in_array($this->container['application_state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'application_state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPushMessageBehaviorAllowableValues();
        if (!is_null($this->container['push_message_behavior']) && !in_array($this->container['push_message_behavior'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'push_message_behavior', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets push_message_token
     *
     * @return string
     */
    public function getPushMessageToken()
    {
        return $this->container['push_message_token'];
    }

    /**
     * Sets push_message_token
     *
     * @param string $push_message_token push_message_token
     *
     * @return $this
     */
    public function setPushMessageToken($push_message_token)
    {
        $this->container['push_message_token'] = $push_message_token;

        return $this;
    }

    /**
     * Gets push_message_type
     *
     * @return string
     */
    public function getPushMessageType()
    {
        return $this->container['push_message_type'];
    }

    /**
     * Sets push_message_type
     *
     * @param string $push_message_type push_message_type
     *
     * @return $this
     */
    public function setPushMessageType($push_message_type)
    {
        $allowedValues = $this->getPushMessageTypeAllowableValues();
        if (!in_array($push_message_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'push_message_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['push_message_type'] = $push_message_type;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets network
     *
     * @return string|null
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string|null $network network
     *
     * @return $this
     */
    public function setNetwork($network)
    {
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets push_notification_payload
     *
     * @return string
     */
    public function getPushNotificationPayload()
    {
        return $this->container['push_notification_payload'];
    }

    /**
     * Sets push_notification_payload
     *
     * @param string $push_notification_payload push_notification_payload
     *
     * @return $this
     */
    public function setPushNotificationPayload($push_notification_payload)
    {
        $this->container['push_notification_payload'] = $push_notification_payload;

        return $this;
    }

    /**
     * Gets application_state
     *
     * @return string|null
     */
    public function getApplicationState()
    {
        return $this->container['application_state'];
    }

    /**
     * Sets application_state
     *
     * @param string|null $application_state application_state
     *
     * @return $this
     */
    public function setApplicationState($application_state)
    {
        $allowedValues = $this->getApplicationStateAllowableValues();
        if (!is_null($application_state) && !in_array($application_state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'application_state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['application_state'] = $application_state;

        return $this;
    }

    /**
     * Gets action_identifier
     *
     * @return string|null
     */
    public function getActionIdentifier()
    {
        return $this->container['action_identifier'];
    }

    /**
     * Sets action_identifier
     *
     * @param string|null $action_identifier action_identifier
     *
     * @return $this
     */
    public function setActionIdentifier($action_identifier)
    {
        $this->container['action_identifier'] = $action_identifier;

        return $this;
    }

    /**
     * Gets push_message_behavior
     *
     * @return string|null
     */
    public function getPushMessageBehavior()
    {
        return $this->container['push_message_behavior'];
    }

    /**
     * Sets push_message_behavior
     *
     * @param string|null $push_message_behavior push_message_behavior
     *
     * @return $this
     */
    public function setPushMessageBehavior($push_message_behavior)
    {
        $allowedValues = $this->getPushMessageBehaviorAllowableValues();
        if (!is_null($push_message_behavior) && !in_array($push_message_behavior, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'push_message_behavior', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['push_message_behavior'] = $push_message_behavior;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


