<?php
/**
 * PushMessageEventData
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PushMessageEventData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PushMessageEventData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PushMessageEventData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'timestamp_unixtime_ms' => 'int',
        'event_id' => 'int',
        'source_message_id' => 'string',
        'session_id' => 'int',
        'session_uuid' => 'string',
        'session_start_unixtime_ms' => 'int',
        'event_start_unixtime_ms' => 'int',
        'custom_attributes' => 'map[string,string]',
        'location' => '\OpenAPI\Client\Model\GeoLocation',
        'device_current_state' => '\OpenAPI\Client\Model\DeviceCurrentState',
        'is_goal_defined' => 'bool',
        'lifetime_value_change' => 'bool',
        'lifetime_value_attribute_name' => 'string',
        'data_connection_type' => 'string',
        'event_num' => 'int',
        'view_controller' => 'string',
        'is_main_thread' => 'bool',
        'canonical_name' => 'string',
        'event_system_notification_info' => '\OpenAPI\Client\Model\EventSystemNotificationInfo',
        'push_message_token' => 'string',
        'push_message_type' => 'string',
        'message' => 'string',
        'network' => 'string',
        'push_notification_payload' => 'string',
        'application_state' => 'string',
        'action_identifier' => 'string',
        'push_message_behavior' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'timestamp_unixtime_ms' => null,
        'event_id' => 'int64',
        'source_message_id' => null,
        'session_id' => 'int64',
        'session_uuid' => null,
        'session_start_unixtime_ms' => null,
        'event_start_unixtime_ms' => null,
        'custom_attributes' => null,
        'location' => null,
        'device_current_state' => null,
        'is_goal_defined' => null,
        'lifetime_value_change' => null,
        'lifetime_value_attribute_name' => null,
        'data_connection_type' => null,
        'event_num' => null,
        'view_controller' => null,
        'is_main_thread' => null,
        'canonical_name' => null,
        'event_system_notification_info' => null,
        'push_message_token' => null,
        'push_message_type' => null,
        'message' => null,
        'network' => null,
        'push_notification_payload' => null,
        'application_state' => null,
        'action_identifier' => null,
        'push_message_behavior' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timestamp_unixtime_ms' => 'timestamp_unixtime_ms',
        'event_id' => 'event_id',
        'source_message_id' => 'source_message_id',
        'session_id' => 'session_id',
        'session_uuid' => 'session_uuid',
        'session_start_unixtime_ms' => 'session_start_unixtime_ms',
        'event_start_unixtime_ms' => 'event_start_unixtime_ms',
        'custom_attributes' => 'custom_attributes',
        'location' => 'location',
        'device_current_state' => 'device_current_state',
        'is_goal_defined' => 'is_goal_defined',
        'lifetime_value_change' => 'lifetime_value_change',
        'lifetime_value_attribute_name' => 'lifetime_value_attribute_name',
        'data_connection_type' => 'data_connection_type',
        'event_num' => 'event_num',
        'view_controller' => 'view_controller',
        'is_main_thread' => 'is_main_thread',
        'canonical_name' => 'canonical_name',
        'event_system_notification_info' => 'event_system_notification_info',
        'push_message_token' => 'push_message_token',
        'push_message_type' => 'push_message_type',
        'message' => 'message',
        'network' => 'network',
        'push_notification_payload' => 'push_notification_payload',
        'application_state' => 'application_state',
        'action_identifier' => 'action_identifier',
        'push_message_behavior' => 'push_message_behavior'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timestamp_unixtime_ms' => 'setTimestampUnixtimeMs',
        'event_id' => 'setEventId',
        'source_message_id' => 'setSourceMessageId',
        'session_id' => 'setSessionId',
        'session_uuid' => 'setSessionUuid',
        'session_start_unixtime_ms' => 'setSessionStartUnixtimeMs',
        'event_start_unixtime_ms' => 'setEventStartUnixtimeMs',
        'custom_attributes' => 'setCustomAttributes',
        'location' => 'setLocation',
        'device_current_state' => 'setDeviceCurrentState',
        'is_goal_defined' => 'setIsGoalDefined',
        'lifetime_value_change' => 'setLifetimeValueChange',
        'lifetime_value_attribute_name' => 'setLifetimeValueAttributeName',
        'data_connection_type' => 'setDataConnectionType',
        'event_num' => 'setEventNum',
        'view_controller' => 'setViewController',
        'is_main_thread' => 'setIsMainThread',
        'canonical_name' => 'setCanonicalName',
        'event_system_notification_info' => 'setEventSystemNotificationInfo',
        'push_message_token' => 'setPushMessageToken',
        'push_message_type' => 'setPushMessageType',
        'message' => 'setMessage',
        'network' => 'setNetwork',
        'push_notification_payload' => 'setPushNotificationPayload',
        'application_state' => 'setApplicationState',
        'action_identifier' => 'setActionIdentifier',
        'push_message_behavior' => 'setPushMessageBehavior'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timestamp_unixtime_ms' => 'getTimestampUnixtimeMs',
        'event_id' => 'getEventId',
        'source_message_id' => 'getSourceMessageId',
        'session_id' => 'getSessionId',
        'session_uuid' => 'getSessionUuid',
        'session_start_unixtime_ms' => 'getSessionStartUnixtimeMs',
        'event_start_unixtime_ms' => 'getEventStartUnixtimeMs',
        'custom_attributes' => 'getCustomAttributes',
        'location' => 'getLocation',
        'device_current_state' => 'getDeviceCurrentState',
        'is_goal_defined' => 'getIsGoalDefined',
        'lifetime_value_change' => 'getLifetimeValueChange',
        'lifetime_value_attribute_name' => 'getLifetimeValueAttributeName',
        'data_connection_type' => 'getDataConnectionType',
        'event_num' => 'getEventNum',
        'view_controller' => 'getViewController',
        'is_main_thread' => 'getIsMainThread',
        'canonical_name' => 'getCanonicalName',
        'event_system_notification_info' => 'getEventSystemNotificationInfo',
        'push_message_token' => 'getPushMessageToken',
        'push_message_type' => 'getPushMessageType',
        'message' => 'getMessage',
        'network' => 'getNetwork',
        'push_notification_payload' => 'getPushNotificationPayload',
        'application_state' => 'getApplicationState',
        'action_identifier' => 'getActionIdentifier',
        'push_message_behavior' => 'getPushMessageBehavior'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const PUSH_MESSAGE_TYPE_SENT = 'sent';
    const PUSH_MESSAGE_TYPE_RECEIVED = 'received';
    const PUSH_MESSAGE_TYPE_ACTION = 'action';
    const APPLICATION_STATE_NOT_RUNNING = 'not_running';
    const APPLICATION_STATE_BACKGROUND = 'background';
    const APPLICATION_STATE_FOREGROUND = 'foreground';
    const PUSH_MESSAGE_BEHAVIOR_RECEIVED = 'Received';
    const PUSH_MESSAGE_BEHAVIOR_DIRECT_OPEN = 'DirectOpen';
    const PUSH_MESSAGE_BEHAVIOR_READ = 'Read';
    const PUSH_MESSAGE_BEHAVIOR_INFLUENCED_OPEN = 'InfluencedOpen';
    const PUSH_MESSAGE_BEHAVIOR_DISPLAYED = 'Displayed';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPushMessageTypeAllowableValues()
    {
        return [
            self::PUSH_MESSAGE_TYPE_SENT,
            self::PUSH_MESSAGE_TYPE_RECEIVED,
            self::PUSH_MESSAGE_TYPE_ACTION,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplicationStateAllowableValues()
    {
        return [
            self::APPLICATION_STATE_NOT_RUNNING,
            self::APPLICATION_STATE_BACKGROUND,
            self::APPLICATION_STATE_FOREGROUND,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPushMessageBehaviorAllowableValues()
    {
        return [
            self::PUSH_MESSAGE_BEHAVIOR_RECEIVED,
            self::PUSH_MESSAGE_BEHAVIOR_DIRECT_OPEN,
            self::PUSH_MESSAGE_BEHAVIOR_READ,
            self::PUSH_MESSAGE_BEHAVIOR_INFLUENCED_OPEN,
            self::PUSH_MESSAGE_BEHAVIOR_DISPLAYED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['timestamp_unixtime_ms'] = isset($data['timestamp_unixtime_ms']) ? $data['timestamp_unixtime_ms'] : null;
        $this->container['event_id'] = isset($data['event_id']) ? $data['event_id'] : null;
        $this->container['source_message_id'] = isset($data['source_message_id']) ? $data['source_message_id'] : null;
        $this->container['session_id'] = isset($data['session_id']) ? $data['session_id'] : null;
        $this->container['session_uuid'] = isset($data['session_uuid']) ? $data['session_uuid'] : null;
        $this->container['session_start_unixtime_ms'] = isset($data['session_start_unixtime_ms']) ? $data['session_start_unixtime_ms'] : null;
        $this->container['event_start_unixtime_ms'] = isset($data['event_start_unixtime_ms']) ? $data['event_start_unixtime_ms'] : null;
        $this->container['custom_attributes'] = isset($data['custom_attributes']) ? $data['custom_attributes'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['device_current_state'] = isset($data['device_current_state']) ? $data['device_current_state'] : null;
        $this->container['is_goal_defined'] = isset($data['is_goal_defined']) ? $data['is_goal_defined'] : null;
        $this->container['lifetime_value_change'] = isset($data['lifetime_value_change']) ? $data['lifetime_value_change'] : null;
        $this->container['lifetime_value_attribute_name'] = isset($data['lifetime_value_attribute_name']) ? $data['lifetime_value_attribute_name'] : null;
        $this->container['data_connection_type'] = isset($data['data_connection_type']) ? $data['data_connection_type'] : null;
        $this->container['event_num'] = isset($data['event_num']) ? $data['event_num'] : null;
        $this->container['view_controller'] = isset($data['view_controller']) ? $data['view_controller'] : null;
        $this->container['is_main_thread'] = isset($data['is_main_thread']) ? $data['is_main_thread'] : null;
        $this->container['canonical_name'] = isset($data['canonical_name']) ? $data['canonical_name'] : null;
        $this->container['event_system_notification_info'] = isset($data['event_system_notification_info']) ? $data['event_system_notification_info'] : null;
        $this->container['push_message_token'] = isset($data['push_message_token']) ? $data['push_message_token'] : null;
        $this->container['push_message_type'] = isset($data['push_message_type']) ? $data['push_message_type'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['network'] = isset($data['network']) ? $data['network'] : null;
        $this->container['push_notification_payload'] = isset($data['push_notification_payload']) ? $data['push_notification_payload'] : null;
        $this->container['application_state'] = isset($data['application_state']) ? $data['application_state'] : null;
        $this->container['action_identifier'] = isset($data['action_identifier']) ? $data['action_identifier'] : null;
        $this->container['push_message_behavior'] = isset($data['push_message_behavior']) ? $data['push_message_behavior'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['push_message_token'] === null) {
            $invalidProperties[] = "'push_message_token' can't be null";
        }
        if ($this->container['push_message_type'] === null) {
            $invalidProperties[] = "'push_message_type' can't be null";
        }
        $allowedValues = $this->getPushMessageTypeAllowableValues();
        if (!is_null($this->container['push_message_type']) && !in_array($this->container['push_message_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'push_message_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['push_notification_payload'] === null) {
            $invalidProperties[] = "'push_notification_payload' can't be null";
        }
        $allowedValues = $this->getApplicationStateAllowableValues();
        if (!is_null($this->container['application_state']) && !in_array($this->container['application_state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'application_state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPushMessageBehaviorAllowableValues();
        if (!is_null($this->container['push_message_behavior']) && !in_array($this->container['push_message_behavior'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'push_message_behavior', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timestamp_unixtime_ms
     *
     * @return int|null
     */
    public function getTimestampUnixtimeMs()
    {
        return $this->container['timestamp_unixtime_ms'];
    }

    /**
     * Sets timestamp_unixtime_ms
     *
     * @param int|null $timestamp_unixtime_ms timestamp_unixtime_ms
     *
     * @return $this
     */
    public function setTimestampUnixtimeMs($timestamp_unixtime_ms)
    {
        $this->container['timestamp_unixtime_ms'] = $timestamp_unixtime_ms;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return int|null
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param int|null $event_id event_id
     *
     * @return $this
     */
    public function setEventId($event_id)
    {
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets source_message_id
     *
     * @return string|null
     */
    public function getSourceMessageId()
    {
        return $this->container['source_message_id'];
    }

    /**
     * Sets source_message_id
     *
     * @param string|null $source_message_id source_message_id
     *
     * @return $this
     */
    public function setSourceMessageId($source_message_id)
    {
        $this->container['source_message_id'] = $source_message_id;

        return $this;
    }

    /**
     * Gets session_id
     *
     * @return int|null
     */
    public function getSessionId()
    {
        return $this->container['session_id'];
    }

    /**
     * Sets session_id
     *
     * @param int|null $session_id session_id
     *
     * @return $this
     */
    public function setSessionId($session_id)
    {
        $this->container['session_id'] = $session_id;

        return $this;
    }

    /**
     * Gets session_uuid
     *
     * @return string|null
     */
    public function getSessionUuid()
    {
        return $this->container['session_uuid'];
    }

    /**
     * Sets session_uuid
     *
     * @param string|null $session_uuid session_uuid
     *
     * @return $this
     */
    public function setSessionUuid($session_uuid)
    {
        $this->container['session_uuid'] = $session_uuid;

        return $this;
    }

    /**
     * Gets session_start_unixtime_ms
     *
     * @return int|null
     */
    public function getSessionStartUnixtimeMs()
    {
        return $this->container['session_start_unixtime_ms'];
    }

    /**
     * Sets session_start_unixtime_ms
     *
     * @param int|null $session_start_unixtime_ms session_start_unixtime_ms
     *
     * @return $this
     */
    public function setSessionStartUnixtimeMs($session_start_unixtime_ms)
    {
        $this->container['session_start_unixtime_ms'] = $session_start_unixtime_ms;

        return $this;
    }

    /**
     * Gets event_start_unixtime_ms
     *
     * @return int|null
     */
    public function getEventStartUnixtimeMs()
    {
        return $this->container['event_start_unixtime_ms'];
    }

    /**
     * Sets event_start_unixtime_ms
     *
     * @param int|null $event_start_unixtime_ms event_start_unixtime_ms
     *
     * @return $this
     */
    public function setEventStartUnixtimeMs($event_start_unixtime_ms)
    {
        $this->container['event_start_unixtime_ms'] = $event_start_unixtime_ms;

        return $this;
    }

    /**
     * Gets custom_attributes
     *
     * @return map[string,string]|null
     */
    public function getCustomAttributes()
    {
        return $this->container['custom_attributes'];
    }

    /**
     * Sets custom_attributes
     *
     * @param map[string,string]|null $custom_attributes custom_attributes
     *
     * @return $this
     */
    public function setCustomAttributes($custom_attributes)
    {
        $this->container['custom_attributes'] = $custom_attributes;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\GeoLocation|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\GeoLocation|null $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets device_current_state
     *
     * @return \OpenAPI\Client\Model\DeviceCurrentState|null
     */
    public function getDeviceCurrentState()
    {
        return $this->container['device_current_state'];
    }

    /**
     * Sets device_current_state
     *
     * @param \OpenAPI\Client\Model\DeviceCurrentState|null $device_current_state device_current_state
     *
     * @return $this
     */
    public function setDeviceCurrentState($device_current_state)
    {
        $this->container['device_current_state'] = $device_current_state;

        return $this;
    }

    /**
     * Gets is_goal_defined
     *
     * @return bool|null
     */
    public function getIsGoalDefined()
    {
        return $this->container['is_goal_defined'];
    }

    /**
     * Sets is_goal_defined
     *
     * @param bool|null $is_goal_defined is_goal_defined
     *
     * @return $this
     */
    public function setIsGoalDefined($is_goal_defined)
    {
        $this->container['is_goal_defined'] = $is_goal_defined;

        return $this;
    }

    /**
     * Gets lifetime_value_change
     *
     * @return bool|null
     */
    public function getLifetimeValueChange()
    {
        return $this->container['lifetime_value_change'];
    }

    /**
     * Sets lifetime_value_change
     *
     * @param bool|null $lifetime_value_change lifetime_value_change
     *
     * @return $this
     */
    public function setLifetimeValueChange($lifetime_value_change)
    {
        $this->container['lifetime_value_change'] = $lifetime_value_change;

        return $this;
    }

    /**
     * Gets lifetime_value_attribute_name
     *
     * @return string|null
     */
    public function getLifetimeValueAttributeName()
    {
        return $this->container['lifetime_value_attribute_name'];
    }

    /**
     * Sets lifetime_value_attribute_name
     *
     * @param string|null $lifetime_value_attribute_name lifetime_value_attribute_name
     *
     * @return $this
     */
    public function setLifetimeValueAttributeName($lifetime_value_attribute_name)
    {
        $this->container['lifetime_value_attribute_name'] = $lifetime_value_attribute_name;

        return $this;
    }

    /**
     * Gets data_connection_type
     *
     * @return string|null
     */
    public function getDataConnectionType()
    {
        return $this->container['data_connection_type'];
    }

    /**
     * Sets data_connection_type
     *
     * @param string|null $data_connection_type data_connection_type
     *
     * @return $this
     */
    public function setDataConnectionType($data_connection_type)
    {
        $this->container['data_connection_type'] = $data_connection_type;

        return $this;
    }

    /**
     * Gets event_num
     *
     * @return int|null
     */
    public function getEventNum()
    {
        return $this->container['event_num'];
    }

    /**
     * Sets event_num
     *
     * @param int|null $event_num event_num
     *
     * @return $this
     */
    public function setEventNum($event_num)
    {
        $this->container['event_num'] = $event_num;

        return $this;
    }

    /**
     * Gets view_controller
     *
     * @return string|null
     */
    public function getViewController()
    {
        return $this->container['view_controller'];
    }

    /**
     * Sets view_controller
     *
     * @param string|null $view_controller view_controller
     *
     * @return $this
     */
    public function setViewController($view_controller)
    {
        $this->container['view_controller'] = $view_controller;

        return $this;
    }

    /**
     * Gets is_main_thread
     *
     * @return bool|null
     */
    public function getIsMainThread()
    {
        return $this->container['is_main_thread'];
    }

    /**
     * Sets is_main_thread
     *
     * @param bool|null $is_main_thread is_main_thread
     *
     * @return $this
     */
    public function setIsMainThread($is_main_thread)
    {
        $this->container['is_main_thread'] = $is_main_thread;

        return $this;
    }

    /**
     * Gets canonical_name
     *
     * @return string|null
     */
    public function getCanonicalName()
    {
        return $this->container['canonical_name'];
    }

    /**
     * Sets canonical_name
     *
     * @param string|null $canonical_name canonical_name
     *
     * @return $this
     */
    public function setCanonicalName($canonical_name)
    {
        $this->container['canonical_name'] = $canonical_name;

        return $this;
    }

    /**
     * Gets event_system_notification_info
     *
     * @return \OpenAPI\Client\Model\EventSystemNotificationInfo|null
     */
    public function getEventSystemNotificationInfo()
    {
        return $this->container['event_system_notification_info'];
    }

    /**
     * Sets event_system_notification_info
     *
     * @param \OpenAPI\Client\Model\EventSystemNotificationInfo|null $event_system_notification_info event_system_notification_info
     *
     * @return $this
     */
    public function setEventSystemNotificationInfo($event_system_notification_info)
    {
        $this->container['event_system_notification_info'] = $event_system_notification_info;

        return $this;
    }

    /**
     * Gets push_message_token
     *
     * @return string
     */
    public function getPushMessageToken()
    {
        return $this->container['push_message_token'];
    }

    /**
     * Sets push_message_token
     *
     * @param string $push_message_token push_message_token
     *
     * @return $this
     */
    public function setPushMessageToken($push_message_token)
    {
        $this->container['push_message_token'] = $push_message_token;

        return $this;
    }

    /**
     * Gets push_message_type
     *
     * @return string
     */
    public function getPushMessageType()
    {
        return $this->container['push_message_type'];
    }

    /**
     * Sets push_message_type
     *
     * @param string $push_message_type push_message_type
     *
     * @return $this
     */
    public function setPushMessageType($push_message_type)
    {
        $allowedValues = $this->getPushMessageTypeAllowableValues();
        if (!in_array($push_message_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'push_message_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['push_message_type'] = $push_message_type;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets network
     *
     * @return string|null
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string|null $network network
     *
     * @return $this
     */
    public function setNetwork($network)
    {
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets push_notification_payload
     *
     * @return string
     */
    public function getPushNotificationPayload()
    {
        return $this->container['push_notification_payload'];
    }

    /**
     * Sets push_notification_payload
     *
     * @param string $push_notification_payload push_notification_payload
     *
     * @return $this
     */
    public function setPushNotificationPayload($push_notification_payload)
    {
        $this->container['push_notification_payload'] = $push_notification_payload;

        return $this;
    }

    /**
     * Gets application_state
     *
     * @return string|null
     */
    public function getApplicationState()
    {
        return $this->container['application_state'];
    }

    /**
     * Sets application_state
     *
     * @param string|null $application_state application_state
     *
     * @return $this
     */
    public function setApplicationState($application_state)
    {
        $allowedValues = $this->getApplicationStateAllowableValues();
        if (!is_null($application_state) && !in_array($application_state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'application_state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['application_state'] = $application_state;

        return $this;
    }

    /**
     * Gets action_identifier
     *
     * @return string|null
     */
    public function getActionIdentifier()
    {
        return $this->container['action_identifier'];
    }

    /**
     * Sets action_identifier
     *
     * @param string|null $action_identifier action_identifier
     *
     * @return $this
     */
    public function setActionIdentifier($action_identifier)
    {
        $this->container['action_identifier'] = $action_identifier;

        return $this;
    }

    /**
     * Gets push_message_behavior
     *
     * @return string|null
     */
    public function getPushMessageBehavior()
    {
        return $this->container['push_message_behavior'];
    }

    /**
     * Sets push_message_behavior
     *
     * @param string|null $push_message_behavior push_message_behavior
     *
     * @return $this
     */
    public function setPushMessageBehavior($push_message_behavior)
    {
        $allowedValues = $this->getPushMessageBehaviorAllowableValues();
        if (!is_null($push_message_behavior) && !in_array($push_message_behavior, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'push_message_behavior', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['push_message_behavior'] = $push_message_behavior;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


