<?php
/**
 * SourceInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SourceInformation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SourceInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SourceInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'channel' => 'string',
        'partner' => 'string',
        'replay_request_id' => 'string',
        'replay_job_id' => 'string',
        'is_historical' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'channel' => null,
        'partner' => null,
        'replay_request_id' => null,
        'replay_job_id' => null,
        'is_historical' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channel' => 'channel',
        'partner' => 'partner',
        'replay_request_id' => 'replay_request_id',
        'replay_job_id' => 'replay_job_id',
        'is_historical' => 'is_historical'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channel' => 'setChannel',
        'partner' => 'setPartner',
        'replay_request_id' => 'setReplayRequestId',
        'replay_job_id' => 'setReplayJobId',
        'is_historical' => 'setIsHistorical'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channel' => 'getChannel',
        'partner' => 'getPartner',
        'replay_request_id' => 'getReplayRequestId',
        'replay_job_id' => 'getReplayJobId',
        'is_historical' => 'getIsHistorical'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const CHANNEL_NATIVE = 'native';
    const CHANNEL_JAVASCRIPT = 'javascript';
    const CHANNEL_PIXEL = 'pixel';
    const CHANNEL_DESKTOP = 'desktop';
    const CHANNEL_PARTNER = 'partner';
    const CHANNEL_SERVER_TO_SERVER = 'server_to_server';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChannelAllowableValues()
    {
        return [
            self::CHANNEL_NATIVE,
            self::CHANNEL_JAVASCRIPT,
            self::CHANNEL_PIXEL,
            self::CHANNEL_DESKTOP,
            self::CHANNEL_PARTNER,
            self::CHANNEL_SERVER_TO_SERVER,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['channel'] = isset($data['channel']) ? $data['channel'] : null;
        $this->container['partner'] = isset($data['partner']) ? $data['partner'] : null;
        $this->container['replay_request_id'] = isset($data['replay_request_id']) ? $data['replay_request_id'] : null;
        $this->container['replay_job_id'] = isset($data['replay_job_id']) ? $data['replay_job_id'] : null;
        $this->container['is_historical'] = isset($data['is_historical']) ? $data['is_historical'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getChannelAllowableValues();
        if (!is_null($this->container['channel']) && !in_array($this->container['channel'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'channel', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channel
     *
     * @return string|null
     */
    public function getChannel()
    {
        return $this->container['channel'];
    }

    /**
     * Sets channel
     *
     * @param string|null $channel channel
     *
     * @return $this
     */
    public function setChannel($channel)
    {
        $allowedValues = $this->getChannelAllowableValues();
        if (!is_null($channel) && !in_array($channel, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'channel', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['channel'] = $channel;

        return $this;
    }

    /**
     * Gets partner
     *
     * @return string|null
     */
    public function getPartner()
    {
        return $this->container['partner'];
    }

    /**
     * Sets partner
     *
     * @param string|null $partner partner
     *
     * @return $this
     */
    public function setPartner($partner)
    {
        $this->container['partner'] = $partner;

        return $this;
    }

    /**
     * Gets replay_request_id
     *
     * @return string|null
     */
    public function getReplayRequestId()
    {
        return $this->container['replay_request_id'];
    }

    /**
     * Sets replay_request_id
     *
     * @param string|null $replay_request_id replay_request_id
     *
     * @return $this
     */
    public function setReplayRequestId($replay_request_id)
    {
        $this->container['replay_request_id'] = $replay_request_id;

        return $this;
    }

    /**
     * Gets replay_job_id
     *
     * @return string|null
     */
    public function getReplayJobId()
    {
        return $this->container['replay_job_id'];
    }

    /**
     * Sets replay_job_id
     *
     * @param string|null $replay_job_id replay_job_id
     *
     * @return $this
     */
    public function setReplayJobId($replay_job_id)
    {
        $this->container['replay_job_id'] = $replay_job_id;

        return $this;
    }

    /**
     * Gets is_historical
     *
     * @return bool|null
     */
    public function getIsHistorical()
    {
        return $this->container['is_historical'];
    }

    /**
     * Sets is_historical
     *
     * @param bool|null $is_historical is_historical
     *
     * @return $this
     */
    public function setIsHistorical($is_historical)
    {
        $this->container['is_historical'] = $is_historical;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


