<?php
/**
 * ApplicationStateTransitionEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ApplicationStateTransitionEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicationStateTransitionEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApplicationStateTransitionEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationStateTransitionEventDataAllOf"
     */
    public function testApplicationStateTransitionEventDataAllOf()
    {
    }

    /**
     * Test attribute "successfully_closed"
     */
    public function testPropertySuccessfullyClosed()
    {
    }

    /**
     * Test attribute "is_first_run"
     */
    public function testPropertyIsFirstRun()
    {
    }

    /**
     * Test attribute "is_upgrade"
     */
    public function testPropertyIsUpgrade()
    {
    }

    /**
     * Test attribute "push_notification_payload"
     */
    public function testPropertyPushNotificationPayload()
    {
    }

    /**
     * Test attribute "launch_referral"
     */
    public function testPropertyLaunchReferral()
    {
    }

    /**
     * Test attribute "application_transition_type"
     */
    public function testPropertyApplicationTransitionType()
    {
    }
}
