<?php
/**
 * BatchUserIdentitiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * BatchUserIdentitiesTest Class Doc Comment
 *
 * @category    Class
 * @description BatchUserIdentities
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatchUserIdentitiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BatchUserIdentities"
     */
    public function testBatchUserIdentities()
    {
    }

    /**
     * Test attribute "other"
     */
    public function testPropertyOther()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {
    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {
    }

    /**
     * Test attribute "google"
     */
    public function testPropertyGoogle()
    {
    }

    /**
     * Test attribute "microsoft"
     */
    public function testPropertyMicrosoft()
    {
    }

    /**
     * Test attribute "yahoo"
     */
    public function testPropertyYahoo()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "facebook_custom_audience_id"
     */
    public function testPropertyFacebookCustomAudienceId()
    {
    }

    /**
     * Test attribute "other_id_2"
     */
    public function testPropertyOtherId2()
    {
    }

    /**
     * Test attribute "other_id_3"
     */
    public function testPropertyOtherId3()
    {
    }

    /**
     * Test attribute "other_id_4"
     */
    public function testPropertyOtherId4()
    {
    }
}
