<?php
/**
 * BatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * BatchTest Class Doc Comment
 *
 * @category    Class
 * @description Batch
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Batch"
     */
    public function testBatch()
    {
    }

    /**
     * Test attribute "source_request_id"
     */
    public function testPropertySourceRequestId()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "device_info"
     */
    public function testPropertyDeviceInfo()
    {
    }

    /**
     * Test attribute "application_info"
     */
    public function testPropertyApplicationInfo()
    {
    }

    /**
     * Test attribute "user_attributes"
     */
    public function testPropertyUserAttributes()
    {
    }

    /**
     * Test attribute "deleted_user_attributes"
     */
    public function testPropertyDeletedUserAttributes()
    {
    }

    /**
     * Test attribute "user_identities"
     */
    public function testPropertyUserIdentities()
    {
    }

    /**
     * Test attribute "environment"
     */
    public function testPropertyEnvironment()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "api_keys"
     */
    public function testPropertyApiKeys()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "integration_attributes"
     */
    public function testPropertyIntegrationAttributes()
    {
    }

    /**
     * Test attribute "partner_identity"
     */
    public function testPropertyPartnerIdentity()
    {
    }

    /**
     * Test attribute "source_info"
     */
    public function testPropertySourceInfo()
    {
    }

    /**
     * Test attribute "mp_deviceid"
     */
    public function testPropertyMpDeviceid()
    {
    }

    /**
     * Test attribute "attribution_info"
     */
    public function testPropertyAttributionInfo()
    {
    }

    /**
     * Test attribute "timestamp_unixtime_ms"
     */
    public function testPropertyTimestampUnixtimeMs()
    {
    }

    /**
     * Test attribute "batch_id"
     */
    public function testPropertyBatchId()
    {
    }

    /**
     * Test attribute "mpid"
     */
    public function testPropertyMpid()
    {
    }

    /**
     * Test attribute "sdk_version"
     */
    public function testPropertySdkVersion()
    {
    }

    /**
     * Test attribute "consent_state"
     */
    public function testPropertyConsentState()
    {
    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {
    }
}
