<?php
/**
 * CommerceEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CommerceEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description CommerceEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CommerceEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommerceEventDataAllOf"
     */
    public function testCommerceEventDataAllOf()
    {
    }

    /**
     * Test attribute "product_action"
     */
    public function testPropertyProductAction()
    {
    }

    /**
     * Test attribute "promotion_action"
     */
    public function testPropertyPromotionAction()
    {
    }

    /**
     * Test attribute "product_impressions"
     */
    public function testPropertyProductImpressions()
    {
    }

    /**
     * Test attribute "shopping_cart"
     */
    public function testPropertyShoppingCart()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "screen_name"
     */
    public function testPropertyScreenName()
    {
    }

    /**
     * Test attribute "is_non_interactive"
     */
    public function testPropertyIsNonInteractive()
    {
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
    }

    /**
     * Test attribute "custom_event_type"
     */
    public function testPropertyCustomEventType()
    {
    }

    /**
     * Test attribute "custom_flags"
     */
    public function testPropertyCustomFlags()
    {
    }
}
