<?php
/**
 * CrashReportEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CrashReportEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description CrashReportEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CrashReportEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CrashReportEventDataAllOf"
     */
    public function testCrashReportEventDataAllOf()
    {
    }

    /**
     * Test attribute "breadcrumbs"
     */
    public function testPropertyBreadcrumbs()
    {
    }

    /**
     * Test attribute "class_name"
     */
    public function testPropertyClassName()
    {
    }

    /**
     * Test attribute "severity"
     */
    public function testPropertySeverity()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "stack_trace"
     */
    public function testPropertyStackTrace()
    {
    }

    /**
     * Test attribute "exception_handled"
     */
    public function testPropertyExceptionHandled()
    {
    }

    /**
     * Test attribute "topmost_context"
     */
    public function testPropertyTopmostContext()
    {
    }

    /**
     * Test attribute "pl_crash_report_file_base64"
     */
    public function testPropertyPlCrashReportFileBase64()
    {
    }

    /**
     * Test attribute "ios_image_base_address"
     */
    public function testPropertyIosImageBaseAddress()
    {
    }

    /**
     * Test attribute "ios_image_size"
     */
    public function testPropertyIosImageSize()
    {
    }

    /**
     * Test attribute "session_number"
     */
    public function testPropertySessionNumber()
    {
    }
}
