<?php
/**
 * CustomEventDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CustomEventDataTest Class Doc Comment
 *
 * @category    Class
 * @description CustomEventData
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomEventDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomEventData"
     */
    public function testCustomEventData()
    {
    }

    /**
     * Test attribute "timestamp_unixtime_ms"
     */
    public function testPropertyTimestampUnixtimeMs()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "source_message_id"
     */
    public function testPropertySourceMessageId()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "session_uuid"
     */
    public function testPropertySessionUuid()
    {
    }

    /**
     * Test attribute "session_start_unixtime_ms"
     */
    public function testPropertySessionStartUnixtimeMs()
    {
    }

    /**
     * Test attribute "event_start_unixtime_ms"
     */
    public function testPropertyEventStartUnixtimeMs()
    {
    }

    /**
     * Test attribute "custom_attributes"
     */
    public function testPropertyCustomAttributes()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "device_current_state"
     */
    public function testPropertyDeviceCurrentState()
    {
    }

    /**
     * Test attribute "is_goal_defined"
     */
    public function testPropertyIsGoalDefined()
    {
    }

    /**
     * Test attribute "lifetime_value_change"
     */
    public function testPropertyLifetimeValueChange()
    {
    }

    /**
     * Test attribute "lifetime_value_attribute_name"
     */
    public function testPropertyLifetimeValueAttributeName()
    {
    }

    /**
     * Test attribute "data_connection_type"
     */
    public function testPropertyDataConnectionType()
    {
    }

    /**
     * Test attribute "event_num"
     */
    public function testPropertyEventNum()
    {
    }

    /**
     * Test attribute "view_controller"
     */
    public function testPropertyViewController()
    {
    }

    /**
     * Test attribute "is_main_thread"
     */
    public function testPropertyIsMainThread()
    {
    }

    /**
     * Test attribute "canonical_name"
     */
    public function testPropertyCanonicalName()
    {
    }

    /**
     * Test attribute "event_system_notification_info"
     */
    public function testPropertyEventSystemNotificationInfo()
    {
    }

    /**
     * Test attribute "custom_event_type"
     */
    public function testPropertyCustomEventType()
    {
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
    }

    /**
     * Test attribute "custom_flags"
     */
    public function testPropertyCustomFlags()
    {
    }
}
