<?php
/**
 * DeviceInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DeviceInformationTest Class Doc Comment
 *
 * @category    Class
 * @description DeviceInformation
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeviceInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeviceInformation"
     */
    public function testDeviceInformation()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {
    }

    /**
     * Test attribute "android_uuid"
     */
    public function testPropertyAndroidUuid()
    {
    }

    /**
     * Test attribute "device_manufacturer"
     */
    public function testPropertyDeviceManufacturer()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "os_version"
     */
    public function testPropertyOsVersion()
    {
    }

    /**
     * Test attribute "device_model"
     */
    public function testPropertyDeviceModel()
    {
    }

    /**
     * Test attribute "screen_height"
     */
    public function testPropertyScreenHeight()
    {
    }

    /**
     * Test attribute "screen_width"
     */
    public function testPropertyScreenWidth()
    {
    }

    /**
     * Test attribute "screen_dpi"
     */
    public function testPropertyScreenDpi()
    {
    }

    /**
     * Test attribute "device_country"
     */
    public function testPropertyDeviceCountry()
    {
    }

    /**
     * Test attribute "locale_language"
     */
    public function testPropertyLocaleLanguage()
    {
    }

    /**
     * Test attribute "locale_country"
     */
    public function testPropertyLocaleCountry()
    {
    }

    /**
     * Test attribute "network_country"
     */
    public function testPropertyNetworkCountry()
    {
    }

    /**
     * Test attribute "network_carrier"
     */
    public function testPropertyNetworkCarrier()
    {
    }

    /**
     * Test attribute "network_code"
     */
    public function testPropertyNetworkCode()
    {
    }

    /**
     * Test attribute "network_mobile_country_code"
     */
    public function testPropertyNetworkMobileCountryCode()
    {
    }

    /**
     * Test attribute "timezone_offset"
     */
    public function testPropertyTimezoneOffset()
    {
    }

    /**
     * Test attribute "build_identifier"
     */
    public function testPropertyBuildIdentifier()
    {
    }

    /**
     * Test attribute "http_header_user_agent"
     */
    public function testPropertyHttpHeaderUserAgent()
    {
    }

    /**
     * Test attribute "ios_advertising_id"
     */
    public function testPropertyIosAdvertisingId()
    {
    }

    /**
     * Test attribute "push_token"
     */
    public function testPropertyPushToken()
    {
    }

    /**
     * Test attribute "cpu_architecture"
     */
    public function testPropertyCpuArchitecture()
    {
    }

    /**
     * Test attribute "is_tablet"
     */
    public function testPropertyIsTablet()
    {
    }

    /**
     * Test attribute "push_notification_sound_enabled"
     */
    public function testPropertyPushNotificationSoundEnabled()
    {
    }

    /**
     * Test attribute "push_notification_vibrate_enabled"
     */
    public function testPropertyPushNotificationVibrateEnabled()
    {
    }

    /**
     * Test attribute "radio_access_technology"
     */
    public function testPropertyRadioAccessTechnology()
    {
    }

    /**
     * Test attribute "supports_telephony"
     */
    public function testPropertySupportsTelephony()
    {
    }

    /**
     * Test attribute "has_nfc"
     */
    public function testPropertyHasNfc()
    {
    }

    /**
     * Test attribute "bluetooth_enabled"
     */
    public function testPropertyBluetoothEnabled()
    {
    }

    /**
     * Test attribute "bluetooth_version"
     */
    public function testPropertyBluetoothVersion()
    {
    }

    /**
     * Test attribute "ios_idfv"
     */
    public function testPropertyIosIdfv()
    {
    }

    /**
     * Test attribute "android_advertising_id"
     */
    public function testPropertyAndroidAdvertisingId()
    {
    }

    /**
     * Test attribute "build_version_release"
     */
    public function testPropertyBuildVersionRelease()
    {
    }

    /**
     * Test attribute "limit_ad_tracking"
     */
    public function testPropertyLimitAdTracking()
    {
    }

    /**
     * Test attribute "amp_id"
     */
    public function testPropertyAmpId()
    {
    }

    /**
     * Test attribute "is_dst"
     */
    public function testPropertyIsDst()
    {
    }

    /**
     * Test attribute "roku_advertising_id"
     */
    public function testPropertyRokuAdvertisingId()
    {
    }

    /**
     * Test attribute "roku_publisher_id"
     */
    public function testPropertyRokuPublisherId()
    {
    }

    /**
     * Test attribute "microsoft_advertising_id"
     */
    public function testPropertyMicrosoftAdvertisingId()
    {
    }

    /**
     * Test attribute "microsoft_publisher_id"
     */
    public function testPropertyMicrosoftPublisherId()
    {
    }

    /**
     * Test attribute "fire_advertising_id"
     */
    public function testPropertyFireAdvertisingId()
    {
    }
}
