<?php
/**
 * DeviceCurrentStateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DeviceCurrentStateTest Class Doc Comment
 *
 * @category    Class
 * @description DeviceCurrentState
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeviceCurrentStateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeviceCurrentState"
     */
    public function testDeviceCurrentState()
    {
    }

    /**
     * Test attribute "time_since_start_ms"
     */
    public function testPropertyTimeSinceStartMs()
    {
    }

    /**
     * Test attribute "battery_level"
     */
    public function testPropertyBatteryLevel()
    {
    }

    /**
     * Test attribute "data_connection_type"
     */
    public function testPropertyDataConnectionType()
    {
    }

    /**
     * Test attribute "data_connection_type_detail"
     */
    public function testPropertyDataConnectionTypeDetail()
    {
    }

    /**
     * Test attribute "gps_state"
     */
    public function testPropertyGpsState()
    {
    }

    /**
     * Test attribute "total_system_memory_usage_bytes"
     */
    public function testPropertyTotalSystemMemoryUsageBytes()
    {
    }

    /**
     * Test attribute "disk_space_free_bytes"
     */
    public function testPropertyDiskSpaceFreeBytes()
    {
    }

    /**
     * Test attribute "external_disk_space_free_bytes"
     */
    public function testPropertyExternalDiskSpaceFreeBytes()
    {
    }

    /**
     * Test attribute "cpu"
     */
    public function testPropertyCpu()
    {
    }

    /**
     * Test attribute "system_memory_available_bytes"
     */
    public function testPropertySystemMemoryAvailableBytes()
    {
    }

    /**
     * Test attribute "system_memory_low"
     */
    public function testPropertySystemMemoryLow()
    {
    }

    /**
     * Test attribute "system_memory_threshold_bytes"
     */
    public function testPropertySystemMemoryThresholdBytes()
    {
    }

    /**
     * Test attribute "application_memory_available_bytes"
     */
    public function testPropertyApplicationMemoryAvailableBytes()
    {
    }

    /**
     * Test attribute "application_memory_max_bytes"
     */
    public function testPropertyApplicationMemoryMaxBytes()
    {
    }

    /**
     * Test attribute "application_memory_total_bytes"
     */
    public function testPropertyApplicationMemoryTotalBytes()
    {
    }

    /**
     * Test attribute "device_orientation"
     */
    public function testPropertyDeviceOrientation()
    {
    }

    /**
     * Test attribute "status_bar_orientation"
     */
    public function testPropertyStatusBarOrientation()
    {
    }
}
