<?php
/**
 * NetworkPerformanceEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * NetworkPerformanceEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description NetworkPerformanceEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NetworkPerformanceEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NetworkPerformanceEventDataAllOf"
     */
    public function testNetworkPerformanceEventDataAllOf()
    {
    }

    /**
     * Test attribute "http_verb"
     */
    public function testPropertyHttpVerb()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "time_elapsed"
     */
    public function testPropertyTimeElapsed()
    {
    }

    /**
     * Test attribute "bytes_in"
     */
    public function testPropertyBytesIn()
    {
    }

    /**
     * Test attribute "bytes_out"
     */
    public function testPropertyBytesOut()
    {
    }

    /**
     * Test attribute "response_code"
     */
    public function testPropertyResponseCode()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }
}
