<?php
/**
 * ProfileEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProfileEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description ProfileEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProfileEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProfileEventDataAllOf"
     */
    public function testProfileEventDataAllOf()
    {
    }

    /**
     * Test attribute "previous_mpid"
     */
    public function testPropertyPreviousMpid()
    {
    }

    /**
     * Test attribute "current_mpid"
     */
    public function testPropertyCurrentMpid()
    {
    }

    /**
     * Test attribute "profile_event_type"
     */
    public function testPropertyProfileEventType()
    {
    }
}
