<?php
/**
 * PushMessageEventDataAllOfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mParticle
 *
 * This is the mParticle Event Server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mparticle.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * PushMessageEventDataAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description PushMessageEventDataAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PushMessageEventDataAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PushMessageEventDataAllOf"
     */
    public function testPushMessageEventDataAllOf()
    {
    }

    /**
     * Test attribute "push_message_token"
     */
    public function testPropertyPushMessageToken()
    {
    }

    /**
     * Test attribute "push_message_type"
     */
    public function testPropertyPushMessageType()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "push_notification_payload"
     */
    public function testPropertyPushNotificationPayload()
    {
    }

    /**
     * Test attribute "application_state"
     */
    public function testPropertyApplicationState()
    {
    }

    /**
     * Test attribute "action_identifier"
     */
    public function testPropertyActionIdentifier()
    {
    }

    /**
     * Test attribute "push_message_behavior"
     */
    public function testPropertyPushMessageBehavior()
    {
    }
}
